import type { CustomerDetail, CustomerPage } from "./types";
const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
function token(): string { if (typeof window === "undefined") return ""; return window.sessionStorage.getItem("admin_access_token") ?? ""; }
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const res = await fetch(`${API}${path}`, { ...init, headers: { "content-type": "application/json", authorization: `Bearer ${token()}`, ...(init.headers ?? {}) }, cache: "no-store" }); if (!res.ok) throw new Error(`customer_api_${res.status}`); return res.json() as Promise<T>; }
export function listCustomers(params: URLSearchParams, signal?: AbortSignal): Promise<CustomerPage> { return request(`/api/v1/admin/customers?${params.toString()}`, { signal }); }
export function getCustomer(id: string): Promise<CustomerDetail> { return request(`/api/v1/admin/customers/${id}`); }
export function lifecycle(id: string, command: string, version: number, reason_code: string, note: string): Promise<unknown> { return request(`/api/v1/admin/customers/${id}/lifecycle/${command}`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ expected_version: version, reason_code, note }) }); }
export function revokeAll(id: string, version: number): Promise<unknown> { return request(`/api/v1/admin/customers/${id}/sessions/revoke-all`, { method: "POST", body: JSON.stringify({ expected_version: version, reason_code: "ADMIN_REVOKE_ALL" }) }); }
export function freezeWallet(id: string, version: number, frozen: boolean): Promise<unknown> { return request(`/api/v1/admin/customers/${id}/wallet/${frozen ? "freeze" : "unfreeze"}`, { method: "POST", body: JSON.stringify({ expected_version: version, reason_code: frozen ? "ADMIN_FREEZE" : "ADMIN_UNFREEZE" }) }); }
export function addNote(id: string, body: string): Promise<unknown> { return request(`/api/v1/admin/customers/${id}/notes`, { method: "POST", body: JSON.stringify({ note_type: "GENERAL", body, pinned: false }) }); }
export function createExport(fields: string[]): Promise<{ export_reference: string; download_reference: string; expires_at: string }> { return request(`/api/v1/admin/customers/exports`, { method: "POST", body: JSON.stringify({ fields, filters: {}, file_format: "CSV" }) }); }
export function createBulk(customer_references: string[], tag_code: string, dry_run = true): Promise<unknown> { return request(`/api/v1/admin/customers/bulk`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ operation: "ADD_TAG", customer_references, parameters: { tag_code }, reason_code: "BULK_TAG", dry_run }) }); }
