export type TelegramTheme = Record<string, string | undefined>;
export type TelegramViewport = { height?: number; stableHeight?: number; safeAreaInsetTop?: number; safeAreaInsetBottom?: number };
type Button = { show?: () => void; hide?: () => void; onClick?: (cb: () => void) => void; offClick?: (cb: () => void) => void; setText?: (text: string) => void };
type WebApp = { initData?: string; version?: string; colorScheme?: "light" | "dark"; themeParams?: TelegramTheme; viewportHeight?: number; viewportStableHeight?: number; safeAreaInset?: { top?: number; bottom?: number }; contentSafeAreaInset?: { top?: number; bottom?: number }; ready?: () => void; expand?: () => void; enableClosingConfirmation?: () => void; disableClosingConfirmation?: () => void; onEvent?: (event: string, cb: () => void) => void; offEvent?: (event: string, cb: () => void) => void; BackButton?: Button; MainButton?: Button };
declare global { interface Window { __VPN_SALE_FAKE_TELEGRAM_INIT_DATA__?: string } }
export type TelegramAdapter = { isAvailable: () => boolean; isSupported: () => boolean; ready: () => void; expand: () => void; getInitData: () => string; getTheme: () => TelegramTheme; getViewport: () => TelegramViewport; onThemeChanged: (cb: () => void) => () => void; onViewportChanged: (cb: () => void) => () => void; setBackButton: (visible: boolean, cb?: () => void) => () => void; setMainButton: (options: { visible: boolean; text?: string; onClick?: () => void }) => () => void; setCloseConfirmation: (enabled: boolean) => void };
function webApp(): WebApp | undefined { return typeof window === "undefined" ? undefined : (window as unknown as {Telegram?:{WebApp?:WebApp}}).Telegram?.WebApp; }
function versionAtLeast(version: string | undefined, major: number): boolean { const found = Number((version ?? "0").split(".")[0]); return Number.isFinite(found) && found >= major; }
export function createTelegramAdapter(): TelegramAdapter { return { isAvailable: () => Boolean(webApp()), isSupported: () => versionAtLeast(webApp()?.version, 6), ready: () => { webApp()?.ready?.(); }, expand: () => { webApp()?.expand?.(); }, getInitData: () => webApp()?.initData ?? "", getTheme: () => ({ ...(webApp()?.themeParams ?? {}), colorScheme: webApp()?.colorScheme }), getViewport: () => ({ height: webApp()?.viewportHeight, stableHeight: webApp()?.viewportStableHeight, safeAreaInsetTop: webApp()?.safeAreaInset?.top ?? webApp()?.contentSafeAreaInset?.top, safeAreaInsetBottom: webApp()?.safeAreaInset?.bottom ?? webApp()?.contentSafeAreaInset?.bottom }), onThemeChanged: (cb) => { webApp()?.onEvent?.("themeChanged", cb); return () => webApp()?.offEvent?.("themeChanged", cb); }, onViewportChanged: (cb) => { webApp()?.onEvent?.("viewportChanged", cb); return () => webApp()?.offEvent?.("viewportChanged", cb); }, setBackButton: (visible, cb) => { const b = webApp()?.BackButton; if (visible) b?.show?.(); else b?.hide?.(); if (cb) b?.onClick?.(cb); return () => { if (cb) b?.offClick?.(cb); b?.hide?.(); }; }, setMainButton: ({ visible, text, onClick }) => { const b = webApp()?.MainButton; if (text) b?.setText?.(text); if (visible) b?.show?.(); else b?.hide?.(); if (onClick) b?.onClick?.(onClick); return () => { if (onClick) b?.offClick?.(onClick); b?.hide?.(); }; }, setCloseConfirmation: (enabled) => { if (enabled) webApp()?.enableClosingConfirmation?.(); else webApp()?.disableClosingConfirmation?.(); } }; }
export function createFakeTelegramAdapter(initData = "test-init-data"): TelegramAdapter { let themeCb: (() => void) | null = null; let viewportCb: (() => void) | null = null; return { isAvailable: () => true, isSupported: () => true, ready: () => undefined, expand: () => undefined, getInitData: () => initData, getTheme: () => ({ bg_color: "#ffffff", text_color: "#111827", colorScheme: "light" }), getViewport: () => ({ height: 720, stableHeight: 680, safeAreaInsetTop: 0, safeAreaInsetBottom: 16 }), onThemeChanged: (cb) => { themeCb = cb; return () => { themeCb = null; }; }, onViewportChanged: (cb) => { viewportCb = cb; return () => { viewportCb = null; }; }, setBackButton: () => () => undefined, setMainButton: () => () => undefined, setCloseConfirmation: () => undefined }; }
