import { refreshOnce } from '../auth/api-client';
import { getAccessToken, getCsrfToken } from '../auth/token-store';
import type { CreditLot, FinancialError, Journal, Page, Policy, Reconciliation, Reservation, Wallet } from './types';
declare const process: { env: { NEXT_PUBLIC_API_BASE_URL?: string } }; const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL??''; type Query=Record<string,string|number|boolean|null|undefined>;
export class FinancialApiError extends Error { detail: FinancialError; constructor(detail:FinancialError){ super(detail.code); this.detail=detail; } }
export function serializeFinanceQuery(q:Query={}):string{ const p=new URLSearchParams(); for(const [k,v] of Object.entries(q)){ if(v!==undefined&&v!==null&&String(v)!=='') p.set(k,String(v).slice(0,160)); } const s=p.toString(); return s?`?${s}`:''; }
async function parseError(r:Response):Promise<FinancialApiError>{ let body:unknown=null; try{body=await r.json();}catch{body=null;} const d=typeof body==='object'&&body&&'detail' in body?(body as {detail?:Record<string,unknown>}).detail:undefined; return new FinancialApiError({status:r.status, code:String(d?.code??`financial_${r.status}`), messageKey:String(d?.message_key??'finance.error.safe'), correlationId:typeof d?.correlation_id==='string'?d.correlation_id:r.headers.get('x-correlation-id')??undefined, retryAfter:r.headers.get('retry-after')}); }
async function request<T>(path:string, init:RequestInit & {csrf?:boolean; retry?:boolean}={}):Promise<T>{ const h=new Headers(init.headers); h.set('accept','application/json'); if(init.body) h.set('content-type','application/json'); const token=getAccessToken(); if(token) h.set('authorization',`Bearer ${token}`); if(init.csrf){ const csrf=getCsrfToken(); if(csrf) h.set('x-csrf-token',csrf); } const res=await fetch(`${API_BASE}/api/v1/admin/management${path}`,{...init,headers:h,credentials:'include',cache:'no-store'}); if(res.status===401&&init.retry!==false){ await refreshOnce(); return request<T>(path,{...init,retry:false}); } if(!res.ok) throw await parseError(res); return res.json() as Promise<T>; }
export const financeApi={ wallets:(q?:Query)=>request<Page<Wallet>>(`/wallets${serializeFinanceQuery(q)}`), wallet:(id:string)=>request<Wallet>(`/wallets/${encodeURIComponent(id)}`), walletTransactions:(id:string,q?:Query)=>request<Page<Journal>>(`/wallets/${encodeURIComponent(id)}/transactions${serializeFinanceQuery(q)}`), credit:(body:Record<string,unknown>, idem:string)=>request<{journal_entry_reference:string}>('/wallets/adjustments/credit',{method:'POST',body:JSON.stringify(body),headers:{'Idempotency-Key':idem},csrf:true}), debit:(body:Record<string,unknown>, idem:string)=>request<{journal_entry_reference:string}>('/wallets/adjustments/debit',{method:'POST',body:JSON.stringify(body),headers:{'Idempotency-Key':idem},csrf:true}), reverse:(journalId:string, idem:string)=>request<{journal_entry_reference:string}>(`/wallets/adjustments/${encodeURIComponent(journalId)}/reverse`,{method:'POST',headers:{'Idempotency-Key':idem},csrf:true}), freeze:(id:string,body:Record<string,unknown>)=>request<{wallet_reference:string;status:string}>(`/wallets/${encodeURIComponent(id)}/freeze`,{method:'POST',body:JSON.stringify(body),csrf:true}), unfreeze:(id:string,body:Record<string,unknown>)=>request<{wallet_reference:string;status:string}>(`/wallets/${encodeURIComponent(id)}/unfreeze`,{method:'POST',body:JSON.stringify(body),csrf:true}), journal:(id:string)=>request<Journal>(`/ledger/journals/${encodeURIComponent(id)}`), journals:(q?:Query)=>request<Page<Journal>>(`/ledger/journals${serializeFinanceQuery(q)}`), credits:(q?:Query)=>request<Page<CreditLot>>(`/wallets/credits${serializeFinanceQuery(q)}`), reservations:(q?:Query)=>request<Page<Reservation>>(`/wallets/reservations${serializeFinanceQuery(q)}`), releaseReservation:(id:string,body:Record<string,unknown>,idem:string)=>request<{reservation_reference:string;status:string}>(`/wallets/reservations/${encodeURIComponent(id)}/release`,{method:'POST',body:JSON.stringify(body),headers:{'Idempotency-Key':idem},csrf:true}), policy:()=>request<Policy>('/wallets/policy/current'), updatePolicy:(body:Policy & {reason:string})=>request<Policy>('/wallets/policy/current',{method:'PUT',body:JSON.stringify(body),csrf:true}), reconcile:(id:string,repair=false)=>request<Reconciliation>(`/wallets/${encodeURIComponent(id)}/reconcile?repair=${repair}`,{method:'POST',csrf:true}) };
