import { expect, test, type Page } from "@playwright/test";
import { mkdir } from "node:fs/promises";

const output = "test-results/screenshots/wallet-ui51";
const profile = { customer_id: "customer-preview", account_status: "ACTIVE", telegram_user_id: 100, username: "preview", account_username: null, first_name: "کاربر", last_name: null, language_code: "fa", created_at: "2026-01-01T00:00:00Z", last_seen_at: null, current_session_id: "session-preview" };
const capabilities = { password_login: false, public_registration: false, telegram_login: true, telegram_linking: false, web_credential_enrollment: false, email_recovery: false, telegram_recovery: false, recovery_codes: false };
const summary = { currency: "IRR", status: "ACTIVE", posted_balance_rial: 2750000, reserved_balance_rial: 250000, available_balance_rial: 2500000, buckets: [{ bucket_type: "CASH", customer_label: "cash", balance_rial: 2000000 }, { bucket_type: "GIFT", customer_label: "gift", balance_rial: 750000 }], updated_at: "2026-07-28T12:00:00Z", has_expiring_credit: false, active_reservation_count: 1 };
const policy = { currency: "IRR", minimum_topup_amount_rial: 1000000, maximum_topup_amount_rial: 500000000, maximum_wallet_balance_rial: 2000000000, customer_wallet_operations_enabled: true, max_transaction_history_page_size: 20 };
const transactions = { items: [{ transaction_reference: "public-transaction-reference", type: "GIFT_CREDIT", direction: "INCOMING", amount_rial: 1000000, currency: "IRR", occurred_at: "2026-07-28T11:00:00Z", status: "POSTED" }], next_cursor: null };
async function mock(page: Page): Promise<void> {
  await page.route("**/telegram-web-app.js?*", (route) => route.fulfill({ contentType: "application/javascript", body: "" }));
  await page.addInitScript(() => { (window as typeof window & { Telegram: unknown }).Telegram = { WebApp: { colorScheme: "dark", version: "8.0", themeParams: {}, initData: "", ready() {}, expand() {}, onEvent() {}, offEvent() {} } }; });
  await page.route("**/api/v1/customer/auth/**", (route) => { const path = new URL(route.request().url()).pathname; return route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(path.endsWith("/capabilities") ? capabilities : path.endsWith("/me") ? profile : []) }); });
  await page.route("**/api/v1/customer/wallet/**", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(new URL(route.request().url()).pathname.endsWith("/policy") ? policy : new URL(route.request().url()).pathname.endsWith("/transactions") ? transactions : { items: [], next_cursor: null }) }));
  await page.route("**/api/v1/customer/wallet", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(summary) }));
  await page.route("**/api/v1/customer/payments/methods?*", (route) => route.fulfill({ status: 200, contentType: "application/json", body: "[]" }));
}
test.beforeAll(async () => mkdir(output, { recursive: true }));
for (const scenario of [{ name: "overview-360-dark", path: "/wallet", width: 360, height: 800 }, { name: "topup-393-dark", path: "/wallet/top-up", width: 393, height: 852 }, { name: "overview-1280-dark", path: "/wallet", width: 1280, height: 800 }] as const) test(scenario.name, async ({ page }) => { await page.setViewportSize(scenario); await mock(page); await page.goto(scenario.path); await expect(page.getByRole("navigation", { name: "بخش‌های اصلی کیف پول" }).getByRole("link")).toHaveCount(3); await expect(page.getByText("تومان").first()).toBeVisible(); await expect(page.locator("body")).not.toContainText("ریال"); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await page.screenshot({ path: `${output}/${scenario.name}.png`, fullPage: true, animations: "disabled" }); });
test("top-up is concise and no method never posts", async ({ page }) => { let posts = 0; await mock(page); page.on("request", (request) => { if (request.method() === "POST" && request.url().includes("wallet-topups")) posts += 1; }); await page.goto("/wallet/top-up"); await expect(page.getByText("حداقل شارژ: ۱۰۰٬۰۰۰ تومان")).toBeVisible(); await expect(page.getByRole("button", { name: "۲٬۰۰۰٬۰۰۰ تومان" })).toBeVisible(); await expect(page.locator("body")).not.toContainText("حداکثر"); await page.getByLabel("مبلغ شارژ").fill("۹۹٬۹۹۹"); await expect(page.getByText("حداقل مبلغ شارژ ۱۰۰٬۰۰۰ تومان است.")).toBeVisible(); await expect(page.getByText("پرداخت آنلاین فعال نیست")).toBeVisible(); expect(posts).toBe(0); });
