import { refreshOnce } from '../auth/api-client';
import { getAccessToken, getCsrfToken } from '../auth/token-store';
import type { CancellationResult, CheckoutSession, CommerceError, Invoice, Order, OutboxEvent, Page, Reconciliation, Reservation, TimelineEvent, WalletPayment } from './types';
import { validateInvoice, validatePage, validateTimeline } from './validation';
declare const process: { env: { NEXT_PUBLIC_API_BASE_URL?: string } }; const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL??''; type Query=Record<string,string|number|boolean|null|undefined>;
export class CommerceApiError extends Error { detail: CommerceError; constructor(detail:CommerceError){ super(detail.code); this.detail=detail; } }
export function serializeCommerceQuery(q:Query={}):string{ const p=new URLSearchParams(); for(const [k,v] of Object.entries(q)){ if(v!==undefined&&v!==null&&String(v)!=='') p.set(k,String(v).slice(0,160)); } const s=p.toString(); return s?`?${s}`:''; }
async function parseError(r:Response):Promise<CommerceApiError>{ let body:unknown=null; try{body=await r.json();}catch{body=null;} const d=typeof body==='object'&&body&&'detail' in body?(body as {detail?:Record<string,unknown>}).detail:undefined; return new CommerceApiError({status:r.status, code:String(d?.code??`commerce_${r.status}`), messageKey:String(d?.message_key??'commerce.error.safe'), correlationId:typeof d?.correlation_id==='string'?d.correlation_id:r.headers.get('x-correlation-id')??undefined, retryAfter:r.headers.get('retry-after')}); }
async function request<T>(path:string, init:RequestInit & {csrf?:boolean; retry?:boolean}={}):Promise<T>{ const h=new Headers(init.headers); h.set('accept','application/json'); if(init.body) h.set('content-type','application/json'); const token=getAccessToken(); if(token) h.set('authorization',`Bearer ${token}`); if(init.csrf){ const csrf=getCsrfToken(); if(csrf) h.set('x-csrf-token',csrf); } const res=await fetch(`${API_BASE}/api/v1/admin/management${path}`,{...init,headers:h,credentials:'include',cache:'no-store'}); if(res.status===401&&init.retry!==false){ await refreshOnce(); return request<T>(path,{...init,retry:false}); } if(!res.ok) throw await parseError(res); return res.json() as Promise<T>; }
export const commerceApi={ overview:()=>request<Record<string,unknown>>('/commerce/overview'), orders:(q?:Query)=>request<Page<Order>>(`/orders${serializeCommerceQuery(q)}`).then(validatePage<Order>), order:(ref:string)=>request<Order>(`/orders/${encodeURIComponent(ref)}`), timeline:(ref:string)=>request<{items:TimelineEvent[]}>(`/orders/${encodeURIComponent(ref)}/timeline`).then(r=>({items:validateTimeline(r.items)})), cancel:(ref:string,body:Record<string,unknown>,idem:string)=>request<CancellationResult>(`/orders/${encodeURIComponent(ref)}/cancel`,{method:'POST',body:JSON.stringify(body),headers:{'Idempotency-Key':idem},csrf:true}), reconcile:(ref:string)=>request<Reconciliation>(`/orders/${encodeURIComponent(ref)}/reconciliation`,{method:'POST',csrf:true}), invoices:(q?:Query)=>request<Page<Invoice>>(`/invoices${serializeCommerceQuery(q)}`).then(validatePage<Invoice>), invoice:(ref:string)=>request<Invoice>(`/invoices/${encodeURIComponent(ref)}`).then(validateInvoice), checkout:(ref:string)=>request<CheckoutSession>(`/checkout/${encodeURIComponent(ref)}`), payment:(ref:string)=>request<WalletPayment>(`/wallet-payments/${encodeURIComponent(ref)}`), reservation:(ref:string)=>request<Reservation>(`/wallet-reservations/${encodeURIComponent(ref)}`), outbox:(q?:Query)=>request<Page<OutboxEvent>>(`/fulfillment-outbox${serializeCommerceQuery(q)}`).then(validatePage<OutboxEvent>), outboxEvent:(ref:string)=>request<OutboxEvent>(`/fulfillment-outbox/${encodeURIComponent(ref)}`) };
