import { correlationId } from "../auth/api-client";
import { getAccessToken } from "../auth/token-store";
import { loadCustomerConfig } from "../config/public-config";
import { assertSafeRial } from "./format";
import type { Page, PaymentAction, PaymentError, PaymentIntent, PaymentMethod, PaymentPurpose, PaymentStatus } from "./types";
type Fetcher=typeof fetch; const config=loadCustomerConfig();
function headers(extra?:HeadersInit):Headers{const h=new Headers(extra);h.set("content-type","application/json");h.set("x-request-id",correlationId());const t=getAccessToken();if(t)h.set("authorization",`Bearer ${t}`);return h;}
function obj(v:unknown):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("invalid_response");return v as Record<string,unknown>}
function str(v:unknown,f:string):string{if(typeof v!=="string")throw new Error(`invalid_${f}`);return v}
function optStr(v:unknown):string|undefined{return typeof v==="string"?v:undefined}
function status(v:unknown):PaymentStatus{const s=str(v,"status");if(!["REQUIRES_CUSTOMER_ACTION","REQUIRES_VERIFICATION","PROCESSING","SUCCEEDED","FAILED","CANCELLED","EXPIRED","RECONCILIATION_REQUIRED"].includes(s))throw new Error("invalid_payment_status");return s as PaymentStatus}
function purpose(v:unknown):PaymentPurpose{const s=str(v,"purpose");if(!["WALLET_TOPUP","ORDER_PAYMENT"].includes(s))throw new Error("invalid_payment_purpose");return s as PaymentPurpose}
function date(v:unknown,f:string):string{const s=str(v,f);if(Number.isNaN(Date.parse(s)))throw new Error(`invalid_${f}`);return s}
function method(v:unknown):PaymentMethod{const o=obj(v);const availability=str(o.availability,"availability");if(!["AVAILABLE","UNAVAILABLE"].includes(availability))throw new Error("invalid_availability");return {code:str(o.code,"code"),display_name:str(o.display_name,"display_name"),description:optStr(o.description),icon_kind:str(o.icon_kind,"icon_kind"),minimum_amount_rial:assertSafeRial(o.minimum_amount_rial,"minimum_amount_rial"),maximum_amount_rial:assertSafeRial(o.maximum_amount_rial,"maximum_amount_rial"),availability:availability as PaymentMethod["availability"]};}
function action(v:unknown):PaymentAction{const o=obj(v);return {intent_reference:str(o.intent_reference,"intent_reference"),status:status(o.status),action_type:str(o.action_type,"action_type") as "REDIRECT",action_url:o.action_url==null?null:str(o.action_url,"action_url"),expires_at:date(o.expires_at,"expires_at"),allowed_hosts:Array.isArray(o.allowed_hosts)?o.allowed_hosts.map(x=>str(x,"allowed_host")):undefined};}
function intent(v:unknown):PaymentIntent{const o=obj(v);if(o.currency!==undefined&&o.currency!=="IRR")throw new Error("invalid_currency");return {reference:optStr(o.reference)??str(o.payment_reference,"payment_reference"),payment_reference:optStr(o.payment_reference),purpose:o.purpose?purpose(o.purpose):undefined,method_label:optStr(o.method_label),method_kind:optStr(o.method_kind),amount_rial:o.amount_rial==null?undefined:assertSafeRial(o.amount_rial,"amount_rial"),currency:o.currency==null?undefined:"IRR",status:status(o.status),created_at:optStr(o.created_at),expires_at:optStr(o.expires_at),succeeded_at:optStr(o.succeeded_at)??null,failed_at:optStr(o.failed_at)??null,cancelled_at:optStr(o.cancelled_at)??null,order_reference:optStr(o.order_reference)??null,invoice_reference:optStr(o.invoice_reference)??null,wallet_transaction_reference:optStr(o.wallet_transaction_reference)??null,settlement_result:o.settlement_result&&typeof o.settlement_result==="object"?o.settlement_result as Record<string,unknown>:null,failure_category:optStr(o.failure_category)??null,correlation_id:optStr(o.correlation_id)??null,can_cancel:o.can_cancel===true,can_retry:o.can_retry===true};}
function page<T>(v:unknown, item:(x:unknown)=>T):Page<T>{const o=obj(v);return {items:Array.isArray(o.items)?o.items.map(item):[],next_cursor:typeof o.next_cursor==="string"?o.next_cursor:null};}
async function err(r:Response):Promise<PaymentError>{const d=await r.json().catch(()=>null) as {detail?:{code?:string;message?:string;correlation_id?:string}}|null;return {code:d?.detail?.code??(r.status===429?"RATE_LIMITED":r.status>=500?"SERVICE_UNAVAILABLE":"PAYMENT_ERROR"),message:d?.detail?.message??"payment_error",retryAfter:r.headers.get("retry-after"),correlationId:d?.detail?.correlation_id};}
async function json<T>(path:string, validate:(v:unknown)=>T, init:RequestInit={}, fetcher:Fetcher=fetch):Promise<T>{const r=await fetcher(`${config.apiBaseUrl}/api/v1/customer/payments${path}`,{...init,headers:headers(init.headers),credentials:"include",cache:"no-store"});if(!r.ok)throw await err(r);return validate(await r.json());}
export const listPaymentMethods=(purposeValue?:PaymentPurpose,signal?:AbortSignal)=>json(`/methods${purposeValue?`?purpose=${purposeValue}`:""}`,(v)=>Array.isArray(v)?v.map(method):page(v,method).items,{signal});
export const createWalletTopupIntent=(amount_rial:number,payment_method_code:string,key:string,signal?:AbortSignal)=>json("/wallet-topups",action,{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify({amount_rial,payment_method_code}),signal});
export const createOrderPaymentIntent=(order_reference:string,payment_method_code:string,key:string,signal?:AbortSignal)=>json(`/orders/${encodeURIComponent(order_reference)}/payment-intents`,action,{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify({order_reference,payment_method_code}),signal});
export const listPaymentIntents=(cursor?:string,signal?:AbortSignal)=>json(`/intents${cursor?`?cursor=${encodeURIComponent(cursor)}`:""}`,(v)=>page(v,intent),{signal});
export const getPaymentIntent=(ref:string,signal?:AbortSignal)=>json(`/intents/${encodeURIComponent(ref)}`,intent,{signal});
export const cancelPaymentIntent=(ref:string,signal?:AbortSignal)=>json(`/intents/${encodeURIComponent(ref)}/cancel`,intent,{method:"POST",body:JSON.stringify({}),signal});
