import { Tech, StatusBadge, ConfirmBox, EmptyState } from '../components/ManagementShell';
import { formatRial, formatToman, ltr, safeDate, safeMetadata } from './format';
import type { PaymentAttempt, PaymentIntent, PaymentMethod, Settlement, Webhook, MethodHealth } from './types';
export function Amount({value}:{value?:number|null}): React.ReactElement { return <span>{formatRial(value)} <small>({formatToman(value)})</small></span>; }
export function Metadata({data}:{data?:Record<string,unknown>}): React.ReactElement { const safe=safeMetadata(data); return <dl>{Object.entries(safe).map(([k,v])=><div key={k}><dt><Tech>{k}</Tech></dt><dd>{v}</dd></div>)}</dl>; }
export function MethodTable({items}:{items:PaymentMethod[]}): React.ReactElement { if(!items.length) return <EmptyState title="روش پرداختی وجود ندارد" body="هیچ داده ساختگی تولید نمی‌شود."/>; return <div className="table-wrap"><table className="data-table"><thead><tr><th>Reference</th><th>کد</th><th>Provider</th><th>Kind</th><th>وضعیت</th><th>ارز</th><th>اهداف</th><th>حداقل/حداکثر</th><th>اولویت</th><th>Credential</th><th>Adapter</th><th>Version</th></tr></thead><tbody>{items.map(m=><tr key={m.method_reference??m.code}><td data-label="Reference"><a href={`/management/payment-methods/${encodeURIComponent(m.method_reference??m.code)}`}><Tech>{m.method_reference??m.code}</Tech></a></td><td data-label="کد"><Tech>{m.code}</Tech></td><td><Tech>{m.provider_code}@{m.adapter_version}</Tech></td><td>{m.method_kind}</td><td><StatusBadge value={m.status??(m.maintenance_mode?'MAINTENANCE':'DRAFT')} /></td><td><Tech>{m.currency}</Tech></td><td>{m.supported_purposes.join('، ')}</td><td><Amount value={m.min_amount_rial}/><br/><Amount value={m.max_amount_rial}/></td><td>{m.priority}</td><td><StatusBadge value={m.credential_state??'not_returned'} /></td><td><StatusBadge value={m.adapter_registered??'registered_unknown'} /></td><td>{m.version??'—'}</td></tr>)}</tbody></table></div>; }
export function IntentTable({items}:{items:PaymentIntent[]}): React.ReactElement { if(!items.length) return <EmptyState title="نیت پرداختی وجود ندارد" body="لیست cursor-paginated از API واقعی پر می‌شود."/>; return <div className="table-wrap"><table className="data-table"><thead><tr><th>Payment</th><th>مشتری</th><th>Purpose</th><th>Method</th><th>مبلغ</th><th>Status</th><th>Attempt</th><th>Settlement</th><th>ایجاد</th><th>انقضا</th></tr></thead><tbody>{items.map(i=><tr key={i.payment_reference}><td><a href={`/management/payment-intents/${i.payment_reference}`}><Tech>{i.payment_reference}</Tech></a></td><td>{i.customer?.display_name??i.customer?.customer_reference??'restricted'}</td><td><Tech>{i.purpose}</Tech></td><td><Tech>{i.method_code??'—'} {i.provider_code}@{i.adapter_version}</Tech></td><td><Amount value={i.amount_rial}/></td><td><StatusBadge value={i.status}/></td><td><StatusBadge value={i.latest_attempt_status}/></td><td><StatusBadge value={i.settlement_state}/></td><td>{safeDate(i.created_at)}</td><td>{safeDate(i.expires_at)}</td></tr>)}</tbody></table></div>; }
export function WebhookTable({items}:{items:Webhook[]}): React.ReactElement { if(!items.length) return <EmptyState title="وبهوکی وجود ندارد" body="raw body و signature هرگز نمایش داده نمی‌شود."/>; return <div className="table-wrap"><table className="data-table"><thead><tr><th>Webhook</th><th>Provider</th><th>دریافت</th><th>Signature</th><th>Processing</th><th>Attempts</th><th>Retry</th><th>Payment</th><th>Correlation</th></tr></thead><tbody>{items.map(w=><tr key={w.webhook_reference}><td><a href={`/management/payment-webhooks/${w.webhook_reference}`}><Tech>{w.webhook_reference}</Tech></a></td><td><Tech>{w.provider_code}@{w.adapter_version}</Tech></td><td>{safeDate(w.received_at)}</td><td><StatusBadge value={w.signature_state}/></td><td><StatusBadge value={w.processing_state}/>{w.dead_letter?<b> dead-letter</b>:null}</td><td>{w.attempt_count}</td><td>{safeDate(w.next_retry_at)}</td><td><Tech>{w.payment_reference}</Tech></td><td><Tech>{w.correlation_id}</Tech></td></tr>)}</tbody></table></div>; }
export function AttemptDetail({a}:{a:PaymentAttempt}): React.ReactElement { return <section className="panel"><h2>Attempt immutable</h2><p><Tech>{a.attempt_reference}</Tech> #{a.attempt_number}</p><StatusBadge value={a.status}/><p>Provider ref: <Tech>{ltr(a.provider_payment_reference)}</Tech></p><p>Verified: <Amount value={a.verified_amount_rial}/> <Tech>{a.verified_currency}</Tech></p>{a.amount_mismatch?<p className="error">هشدار بحرانی: amount mismatch</p>:null}{a.currency_mismatch?<p className="error">هشدار بحرانی: currency mismatch</p>:null}<Metadata data={a.sanitized_metadata}/></section>; }
export function SettlementDetail({s}:{s:Settlement}): React.ReactElement { return <section className="panel"><h2>Settlement read-only immutable</h2><p><Tech>{s.settlement_reference}</Tech></p><p><Amount value={s.settled_amount_rial}/> <Tech>{s.currency}</Tech></p><StatusBadge value={s.status}/><p>Ledger: {s.ledger_restricted?'restricted':<Tech>{s.ledger_journal_reference}</Tech>}</p><p>{s.result_type}: <Tech>{s.result_reference}</Tech></p></section>; }
export function HealthCard({h}:{h:MethodHealth}): React.ReactElement { return <section className="panel"><h2>Method health authoritative</h2><StatusBadge value={h.availability}/><p>Policy <Tech>{h.policy_state}</Tech></p><p>Credential <Tech>{h.credential_state}</Tech>; Adapter <Tech>{String(h.adapter_registered)}</Tech>; Maintenance <Tech>{String(h.maintenance_mode)}</Tech></p><p>Webhook backlog: <Tech>{h.webhook_backlog_state}</Tech>; Verification backlog: <Tech>{h.verification_backlog_state}</Tech></p></section>; }
export { ConfirmBox };
