import React from "react";
type Tone="neutral"|"primary"|"success"|"warning"|"danger"|"info"; const cx=(...v:Array<string|false|undefined>)=>v.filter(Boolean).join(" ");
export type ButtonProps=React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"|"danger";loading?:boolean};
export const Button=React.forwardRef<HTMLButtonElement,ButtonProps>(function Button({variant="primary",loading,disabled,className,children,...p},ref){return <button ref={ref} className={cx("ui-button",`ui-button--${variant}`,className)} disabled={disabled||loading} aria-busy={loading||undefined}{...p}>{loading&&<Spinner label=""/>}{children}</button>});
export const IconButton=React.forwardRef<HTMLButtonElement,ButtonProps>(function IconButton(p,ref){return <Button {...p} ref={ref} className={cx("ui-icon-button",p.className)}/>});
export function LinkButton({variant="primary",className,...p}:React.AnchorHTMLAttributes<HTMLAnchorElement>&{variant?:ButtonProps["variant"]}){return <a className={cx("ui-button",`ui-button--${variant}`,className)} {...p}/>}
export const Input=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function Input({className,...p},ref){return <input ref={ref} className={cx("ui-input",className)} {...p}/>});
export const PasswordInput=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function PasswordInput(p,ref){return <Input {...p} ref={ref} type="password"/>});
export const SearchInput=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function SearchInput(p,ref){return <Input {...p} ref={ref} type="search"/>});
export const Textarea=React.forwardRef<HTMLTextAreaElement,React.TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({className,...p},ref){return <textarea ref={ref} className={cx("ui-input",className)} {...p}/>});
export const Select=React.forwardRef<HTMLSelectElement,React.SelectHTMLAttributes<HTMLSelectElement>>(function Select({className,...p},ref){return <select ref={ref} className={cx("ui-input",className)} {...p}/>});
export function Field({label,hint,error,children}:{label:React.ReactNode;hint?:React.ReactNode;error?:React.ReactNode;children:React.ReactElement}){const id=React.useId();return <label className="ui-field"><span>{label}</span>{React.cloneElement(children as React.ReactElement<{"aria-describedby"?:string;"aria-invalid"?:boolean}>,{"aria-describedby":hint||error?id:undefined,"aria-invalid":!!error||undefined})}<small id={id} className={error?"ui-danger":"ui-muted"}>{error??hint}</small></label>}
export function FormMessage({tone="neutral",children}:{tone?:Tone;children:React.ReactNode}){return <p className={cx("ui-form-message",`ui-${tone}`)} role={tone==="danger"?"alert":"status"}>{children}</p>}
export const Checkbox=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function Checkbox(p,ref){return <input {...p} ref={ref} type="checkbox" className={cx("ui-check",p.className)}/>});
export const Radio=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function Radio(p,ref){return <input {...p} ref={ref} type="radio" className={cx("ui-check",p.className)}/>});
export const Switch=React.forwardRef<HTMLInputElement,Omit<React.InputHTMLAttributes<HTMLInputElement>,"type">>(function Switch(p,ref){return <input {...p} ref={ref} type="checkbox" role="switch" className={cx("ui-switch",p.className)}/>});
export function Badge({tone="neutral",children}:{tone?:Tone;children:React.ReactNode}){return <span className={cx("ui-badge",`ui-${tone}`)}>{children}</span>} export const StatusBadge=Badge; export function RoleBadge({role}:{role:string}){return <Badge tone="info">{role}</Badge>}
export function Avatar({name,src}:{name:string;src?:string}){return src?<img className="ui-avatar" src={src} alt={name}/>:<span className="ui-avatar" aria-label={name}>{name.trim().slice(0,1)}</span>}
export function Card({interactive,className,...p}:React.HTMLAttributes<HTMLElement>&{interactive?:boolean}){return <article className={cx("ui-card",interactive&&"ui-card--interactive",className)} {...p}/>} export function InteractiveCard(p:React.AnchorHTMLAttributes<HTMLAnchorElement>){return <a {...p} className={cx("ui-card","ui-card--interactive",p.className)}/>}
export function StatCard({label,value,detail}:{label:React.ReactNode;value:React.ReactNode;detail?:React.ReactNode}){return <Card><span className="ui-muted">{label}</span><strong className="ui-stat">{value}</strong>{detail&&<small>{detail}</small>}</Card>}
export function Alert({title,tone="info",children}:{title:string;tone?:Tone;children?:React.ReactNode}){return <section className={cx("ui-alert",`ui-${tone}`)} role={tone==="danger"?"alert":"status"}><strong>{title}</strong>{children}</section>}
export function EmptyState({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <section className="ui-empty"><h3>{title}</h3>{description&&<p>{description}</p>}{action}</section>}
export function Skeleton({label="Loading"}:{label?:string}){return <span className="ui-skeleton" role="status"><span className="ui-sr-only">{label}</span></span>} export function Spinner({label="Loading"}:{label?:string}){return <span className="ui-spinner" role="status" aria-label={label||undefined}/>} export function Progress({value,label}:{value:number;label:string}){return <label className="ui-field"><span>{label}</span><progress max={100} value={Math.max(0,Math.min(100,value))}/></label>}
export type NavigationItem={label:string;href:string;icon?:React.ReactNode;current?:boolean};
export function Tabs({label,items,active}:{label:string;items:Array<{id:string;label:string;href:string}>;active:string}){return <nav className="ui-tabs" aria-label={label}>{items.map(x=><a key={x.id} href={x.href} aria-current={x.id===active?"page":undefined}>{x.label}</a>)}</nav>}
export function SegmentedControl({label,children}:{label:string;children:React.ReactNode}){return <div className="ui-segmented" role="group" aria-label={label}>{children}</div>}
export function Breadcrumb({items}:{items:Array<{label:string;href?:string}>}){return <nav aria-label="Breadcrumb"><ol className="ui-breadcrumb">{items.map((x,i)=><li key={i}>{x.href?<a href={x.href}>{x.label}</a>:<span aria-current="page">{x.label}</span>}</li>)}</ol></nav>}
export function DropdownMenu({label,children}:{label:string;children:React.ReactNode}){return <details className="ui-menu"><summary>{label}</summary><div role="menu">{children}</div></details>}
export function Modal({open,title,onClose,children}:{open:boolean;title:string;onClose:()=>void;children:React.ReactNode}){const r=React.useRef<HTMLDialogElement>(null);React.useEffect(()=>{const d=r.current;if(!d)return;if(open&&!d.open)d.showModal();if(!open&&d.open)d.close()},[open]);return <dialog ref={r} className="ui-dialog" onClose={onClose} aria-labelledby="ui-dialog-title"><h2 id="ui-dialog-title">{title}</h2>{children}<Button variant="ghost" onClick={onClose}>×</Button></dialog>}
export function ConfirmDialog({open,title,description,confirmLabel,cancelLabel,onConfirm,onClose}:{open:boolean;title:string;description:string;confirmLabel:string;cancelLabel:string;onConfirm:()=>void;onClose:()=>void}){return <Modal open={open} title={title} onClose={onClose}><p>{description}</p><div className="ui-actions"><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button><Button variant="secondary" onClick={onClose}>{cancelLabel}</Button></div></Modal>}
export function Drawer(p:Parameters<typeof Modal>[0]){return <Modal {...p}/>} export const BottomSheet=Drawer; export function Toast({children,tone="info"}:{children:React.ReactNode;tone?:Tone}){return <div className={cx("ui-toast",`ui-${tone}`)} role="status">{children}</div>} export function Tooltip({label,children}:{label:string;children:React.ReactElement}){return <span className="ui-tooltip" data-tooltip={label}>{children}</span>}
export function Pagination({page,pages,href}:{page:number;pages:number;href:(p:number)=>string}){return <nav className="ui-pagination" aria-label="Pagination"><a href={href(page-1)} aria-disabled={page<=1}>‹</a><span>{page} / {pages}</span><a href={href(page+1)} aria-disabled={page>=pages}>›</a></nav>}
export function DataTable({caption,headers,rows}:{caption:string;headers:string[];rows:React.ReactNode[][]}){return <div className="ui-table-wrap"><table className="ui-table"><caption>{caption}</caption><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} data-label={headers[j]}>{c}</td>)}</tr>)}</tbody></table></div>}
export function CommandMenu({label,placeholder}:{label:string;placeholder:string}){return <form className="ui-command" role="search"><label className="ui-sr-only" htmlFor="ui-command">{label}</label><SearchInput id="ui-command" placeholder={placeholder}/></form>}
export function PageHeader({eyebrow,title,actions}:{eyebrow?:string;title:string;actions?:React.ReactNode}){return <header className="ui-page-header"><div>{eyebrow&&<p className="ui-eyebrow">{eyebrow}</p>}<h1>{title}</h1></div>{actions}</header>} export function SectionHeader({title,action}:{title:string;action?:React.ReactNode}){return <header className="ui-section-header"><h2>{title}</h2>{action}</header>}
export function Sidebar({label,brand,items,footer}:{label:string;brand:React.ReactNode;items:NavigationItem[];footer?:React.ReactNode}){return <aside className="ui-sidebar"><div className="ui-brand">{brand}</div><nav aria-label={label}>{items.map(x=><a key={x.href} href={x.href} aria-current={x.current?"page":undefined}>{x.icon}{x.label}</a>)}</nav>{footer}</aside>}
export function MobileNavigation({label,items}:{label:string;items:NavigationItem[]}){return <nav className="ui-mobile-nav" aria-label={label}>{items.map(x=><a key={x.href} href={x.href} aria-current={x.current?"page":undefined}>{x.icon}<span>{x.label}</span></a>)}</nav>}
export function AppShell({sidebar,mobileNavigation,children,density="comfortable"}:{sidebar:React.ReactNode;mobileNavigation:React.ReactNode;children:React.ReactNode;density?:"comfortable"|"compact"}){return <div className={cx("ui-app-shell",`ui-app-shell--${density}`)}>{sidebar}<main id="main-content" className="ui-main">{children}</main>{mobileNavigation}</div>} export function UserMenu({name,role}:{name:string;role?:string}){return <DropdownMenu label={name}><span role="menuitem">{role}</span></DropdownMenu>}
