import {afterEach,describe,expect,it,vi} from "vitest";
import {createTelegramWebApp,synchronizeTelegramCssVariables,versionAtLeast} from "../src/index";
afterEach(()=>{delete (globalThis as {window?:unknown}).window});
const mock=()=>{const listeners=new Map<string,Set<(...a:unknown[])=>void>>();const callbacks=new Set<()=>void>();const button={show:vi.fn(),hide:vi.fn(),setText:vi.fn(),enable:vi.fn(),disable:vi.fn(),showProgress:vi.fn(),hideProgress:vi.fn(),onClick:vi.fn((cb:()=>void)=>callbacks.add(cb)),offClick:vi.fn((cb:()=>void)=>callbacks.delete(cb))};const webApp={version:"7.10",initData:"raw-for-server-verification",ready:vi.fn(),expand:vi.fn(),themeParams:{bg_color:"#000"},viewportStableHeight:700,safeAreaInset:{bottom:20},contentSafeAreaInset:{top:4},onEvent:vi.fn((n:string,cb:(...a:unknown[])=>void)=>{const s=listeners.get(n)??new Set();s.add(cb);listeners.set(n,s)}),offEvent:vi.fn((n:string,cb:(...a:unknown[])=>void)=>listeners.get(n)?.delete(cb)),BackButton:button,MainButton:button,SecondaryButton:button,enableClosingConfirmation:vi.fn(),disableClosingConfirmation:vi.fn()};(globalThis as any).window={Telegram:{WebApp:webApp}};return{webApp,listeners,callbacks,button}};
describe("Telegram adapter",()=>{
 it("is SSR and browser safe",()=>{expect(createTelegramWebApp().available()).toBe(false);(globalThis as any).window={};expect(createTelegramWebApp().available()).toBe(false)});
 it.each([["7","7.0",true],["7.0","7",true],["7.10","7.2",true],["8.0","7.10",true],["10.2","8.0",true],["oops","7",false]])("compares %s with %s",(a,b,want)=>expect(versionAtLeast(a,b)).toBe(want));
 it("calls ready and expand",()=>{const{webApp}=mock();const app=createTelegramWebApp();app.ready();app.expand();expect(webApp.ready).toHaveBeenCalledOnce();expect(webApp.expand).toHaveBeenCalledOnce()});
 it("removes the exact event callback once",()=>{const{webApp}=mock();const cb=vi.fn();const off=createTelegramWebApp().onThemeChanged(cb);off();off();expect(webApp.offEvent).toHaveBeenCalledOnce();expect(webApp.offEvent).toHaveBeenCalledWith("themeChanged",cb)});
 it("owns button callbacks without duplication",()=>{const{button}=mock();const cb=vi.fn();const app=createTelegramWebApp();const a=app.setMainButton({visible:true,onClick:cb,enabled:false,loading:true});const b=app.setMainButton({visible:true,onClick:cb});expect(button.onClick).toHaveBeenCalledOnce();a();expect(button.offClick).toHaveBeenCalledWith(cb);b();expect(button.offClick).toHaveBeenCalledOnce()});
 it("synchronizes theme, viewport, safe area and cleanup",()=>{const{listeners,webApp}=mock();const root=document.createElement("div");const app=createTelegramWebApp();const clean=synchronizeTelegramCssVariables(root,app);expect(root.style.getPropertyValue("--app-height")).toBe("700px");expect(root.style.getPropertyValue("--tg-safe-bottom")).toBe("20px");webApp.themeParams={bg_color:"#fff"};listeners.get("themeChanged")?.forEach(cb=>cb());expect(root.style.getPropertyValue("--tg-theme-bg-color")).toBe("#fff");clean();expect(listeners.get("themeChanged")?.size).toBe(0);expect(listeners.get("viewportChanged")?.size).toBe(0)});
 it("toggles closing confirmation",()=>{const{webApp}=mock();const app=createTelegramWebApp();app.setClosingConfirmation(true);app.setClosingConfirmation(false);expect(webApp.enableClosingConfirmation).toHaveBeenCalledOnce();expect(webApp.disableClosingConfirmation).toHaveBeenCalledOnce()});
 it("returns unsupported storage and rejects sensitive key and value",async()=>{mock();const app=createTelegramWebApp();expect(await app.setStorageItem("device","theme","dark")).toEqual({ok:false,reason:"unsupported"});expect(await app.setStorageItem("device","access_token","x")).toEqual({ok:false,reason:"forbidden"});expect(await app.setStorageItem("device","preference","Bearer secret-value")).toEqual({ok:false,reason:"forbidden"});expect(await app.setStorageItem("device","raw","eyJabcdef.eyJabcdef.signature")).toEqual({ok:false,reason:"forbidden"})});
 it("supports storage callbacks and errors",async()=>{const{webApp}=mock();webApp.DeviceStorage={setItem:(_k:string,_v:string,cb?:(e?:string|null)=>void)=>cb?.(),getItem:(_k:string,cb:(e:string|null,v?:string)=>void)=>cb(null,"dark"),removeItem:(_k:string,cb?:(e?:string|null)=>void)=>cb?.("failed")};const app=createTelegramWebApp();expect(await app.setStorageItem("device","theme","dark")).toEqual({ok:true,value:undefined});expect(await app.getStorageItem("device","theme")).toEqual({ok:true,value:"dark"});expect(await app.removeStorageItem("device","theme")).toEqual({ok:false,reason:"error",error:"failed"})});
 it("exposes only raw initData and no unsafe identity API",()=>{mock();const app=createTelegramWebApp();expect(app.rawInitData()).toBe("raw-for-server-verification");expect("initDataUnsafe" in app).toBe(false)});
});
