import { refreshOnce } from "../auth/api-client";
import { getAccessToken, getCsrfToken } from "../auth/token-store";
import type { CatalogError, Category, CursorPage, PreviewResult, PriceList, PricingRule, Product, ProductVersion } from "./types";
declare const process: { env: { NEXT_PUBLIC_API_BASE_URL?: string } };
const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";
type Query = Record<string,string|number|boolean|null|undefined>;
export class CatalogApiError extends Error { detail: CatalogError; constructor(detail: CatalogError){ super(detail.code); this.detail = detail; } }
export const catalogKeys = { categories:["catalog","categories"] as const, products:["catalog","products"] as const, priceLists:["catalog","price-lists"] as const, preview:["catalog","preview"] as const };
export function serializeCatalogQuery(query: Query = {}): string { const p = new URLSearchParams(); for (const [k,v] of Object.entries(query)) if (v !== undefined && v !== null && String(v) !== "") p.set(k, String(v).slice(0,240)); const s = p.toString(); return s ? `?${s}` : ""; }
async function parseError(response: Response): Promise<CatalogApiError> { let body: unknown = null; try { body = await response.json(); } catch { body = null; } const d = typeof body === "object" && body && "detail" in body ? (body as { detail?: Record<string, unknown> }).detail : undefined; return new CatalogApiError({ status: response.status, code: String(d?.code ?? `catalog_${response.status}`), messageKey: String(d?.message_key ?? "catalog.unknown"), correlationId: typeof d?.correlation_id === "string" ? d.correlation_id : response.headers.get("x-correlation-id") ?? undefined, fields: typeof d?.fields === "object" && d.fields ? d.fields as Record<string,string> : {}, retryAfter: response.headers.get("retry-after") }); }
async function request<T>(path: string, init: RequestInit & { csrf?: boolean; retry?: boolean } = {}): Promise<T> { const headers = new Headers(init.headers); headers.set("accept","application/json"); headers.set("x-correlation-id", crypto.randomUUID()); if (init.body) headers.set("content-type","application/json"); const token = getAccessToken(); if (token) headers.set("authorization", `Bearer ${token}`); if (init.csrf) { const csrf = getCsrfToken(); if (csrf) headers.set("x-csrf-token", csrf); } const res = await fetch(`${API_BASE}/api/v1/admin/catalog${path}`, { ...init, headers, credentials:"include" }); if (res.status === 401 && init.retry !== false) { await refreshOnce(); return request<T>(path, { ...init, retry:false }); } if (!res.ok) throw await parseError(res); return res.json() as Promise<T>; }
export const catalogApi = {
 categories: (q?: Query, signal?: AbortSignal) => request<CursorPage<Category>>(`/categories${serializeCatalogQuery(q)}`, { signal }), createCategory: (body: Record<string,unknown>) => request<Category>("/categories", { method:"POST", body: JSON.stringify(body), csrf:true }), activateCategory: (id:string) => request<Category>(`/categories/${encodeURIComponent(id)}/activate`, { method:"POST", csrf:true }),
 products: (q?: Query, signal?: AbortSignal) => request<CursorPage<Product>>(`/products${serializeCatalogQuery(q)}`, { signal }), createProduct: (body: Record<string,unknown>) => request<Product>("/products", { method:"POST", body: JSON.stringify(body), csrf:true }), createVersion: (productId:string, body: Record<string,unknown>) => request<ProductVersion>(`/products/${encodeURIComponent(productId)}/versions`, { method:"POST", body: JSON.stringify(body), csrf:true }), publishVersion: (productId:string, versionId:string) => request<ProductVersion>(`/products/${encodeURIComponent(productId)}/versions/${encodeURIComponent(versionId)}/publish`, { method:"POST", csrf:true }), pauseProduct: (productId:string, reason:string) => request<Product>(`/products/${encodeURIComponent(productId)}/pause`, { method:"POST", body: JSON.stringify({ reason }), csrf:true }),
 createPriceList: (body: Record<string,unknown>) => request<PriceList>("/price-lists", { method:"POST", body: JSON.stringify(body), csrf:true }), createPriceListVersion: (id:string, body: Record<string,unknown>) => request<Record<string,unknown>>(`/price-lists/${encodeURIComponent(id)}/versions`, { method:"POST", body: JSON.stringify(body), csrf:true }), createRule: (versionId:string, body: PricingRule) => request<PricingRule>(`/price-list-versions/${encodeURIComponent(versionId)}/rules`, { method:"POST", body: JSON.stringify(body), csrf:true }), preview: (body: Record<string,unknown>) => request<PreviewResult>("/preview", { method:"POST", body: JSON.stringify(body), csrf:true })
};

export const previewAuthority = "server pricing engine";
