import { correlationId } from "../auth/api-client";
import { getAccessToken } from "../auth/token-store";
import { loadCustomerConfig } from "../config/public-config";
import { assertSafeRial } from "./format";
import type { CreditLot, Page, Reservation, Transaction, WalletError, WalletPolicy, WalletSummary, WalletStatus } from "./types";
type Fetcher = typeof fetch; const config = loadCustomerConfig(); const inFlight = new Map<string, Promise<unknown>>();
function headers(): Headers { const h = new Headers(); h.set("content-type", "application/json"); h.set("x-request-id", correlationId()); const token = getAccessToken(); if (token) h.set("authorization", `Bearer ${token}`); return h; }
async function parseError(r: Response): Promise<WalletError> { let code = r.status === 401 ? "AUTHENTICATION_REQUIRED" : r.status === 503 ? "SERVICE_UNAVAILABLE" : "WALLET_ERROR"; let cid: string | undefined; const detail = await r.json().catch(() => null) as { detail?: { code?: string; correlation_id?: string } } | null; if (detail?.detail?.code) code = detail.detail.code; if (detail?.detail?.correlation_id) cid = detail.detail.correlation_id; return { code, message: code, correlationId: cid, retryAfter: r.headers.get("retry-after") }; }
async function json<T>(path: string, validate: (v: unknown) => T, init: RequestInit = {}, fetcher: Fetcher = fetch): Promise<T> { const r = await fetcher(`${config.apiBaseUrl}/api/v1/customer/wallet${path}`, { ...init, headers: headers(), credentials: "include", cache: "no-store" }); if (!r.ok) throw await parseError(r); return validate(await r.json()); }
function dedupe<T>(key: string, load: () => Promise<T>): Promise<T> { if (!inFlight.has(key)) inFlight.set(key, load().finally(() => inFlight.delete(key))); return inFlight.get(key) as Promise<T>; }
function str(v: unknown, f: string): string { if (typeof v !== "string") throw new Error(`invalid_${f}`); return v; }
function date(v: unknown, f: string): string { const s = str(v, f); if (Number.isNaN(Date.parse(s))) throw new Error(`invalid_${f}`); return s; }
function optDate(v: unknown, f: string): string | null { return v == null ? null : date(v, f); }
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== "object" || Array.isArray(v)) throw new Error("invalid_response"); return v as Record<string, unknown>; }
function status(v: unknown): WalletStatus { const s = str(v, "status"); if (!["ACTIVE","FROZEN","CLOSED"].includes(s)) throw new Error("invalid_wallet_status"); return s as WalletStatus; }
export function validateSummary(v: unknown): WalletSummary { const o = obj(v); if (o.currency !== "IRR") throw new Error("invalid_currency"); const posted = assertSafeRial(o.posted_balance_rial, "posted_balance_rial"); const reserved = assertSafeRial(o.reserved_balance_rial, "reserved_balance_rial"); const available = assertSafeRial(o.available_balance_rial, "available_balance_rial"); if (posted < reserved || available + reserved !== posted) throw new Error("projection_mismatch"); const buckets = Array.isArray(o.buckets) ? o.buckets.map((b) => { const bo = obj(b); return { bucket_type: str(bo.bucket_type, "bucket_type"), customer_label: str(bo.customer_label, "customer_label"), balance_rial: assertSafeRial(bo.balance_rial, "bucket_balance_rial"), expires_at: optDate(bo.expires_at, "bucket_expires_at") }; }) : []; return { currency: "IRR", status: status(o.status), posted_balance_rial: posted, reserved_balance_rial: reserved, available_balance_rial: available, buckets, updated_at: date(o.updated_at, "updated_at"), has_expiring_credit: o.has_expiring_credit === true, active_reservation_count: assertSafeRial(o.active_reservation_count, "active_reservation_count") }; }
export function validatePolicy(v: unknown): WalletPolicy { const o = obj(v); if (o.currency !== "IRR") throw new Error("invalid_currency"); return { currency: "IRR", minimum_topup_amount_rial: assertSafeRial(o.minimum_topup_amount_rial, "minimum_topup_amount_rial"), maximum_topup_amount_rial: assertSafeRial(o.maximum_topup_amount_rial, "maximum_topup_amount_rial"), maximum_wallet_balance_rial: o.maximum_wallet_balance_rial == null ? undefined : assertSafeRial(o.maximum_wallet_balance_rial, "maximum_wallet_balance_rial"), customer_wallet_operations_enabled: o.customer_wallet_operations_enabled === true, max_transaction_history_page_size: assertSafeRial(o.max_transaction_history_page_size, "max_transaction_history_page_size"), default_reservation_lifetime_seconds: typeof o.default_reservation_lifetime_seconds === "number" ? o.default_reservation_lifetime_seconds : undefined }; }
function validateTx(v: unknown): Transaction { const o = obj(v); if (o.currency !== "IRR") throw new Error("invalid_currency"); return { transaction_reference: str(o.transaction_reference, "transaction_reference"), type: str(o.type, "type"), direction: typeof o.direction === "string" ? o.direction as Transaction["direction"] : undefined, amount_rial: o.amount_rial == null ? undefined : assertSafeRial(o.amount_rial, "amount_rial"), currency: "IRR", occurred_at: date(o.occurred_at, "occurred_at"), posted_at: optDate(o.posted_at, "posted_at"), status: str(o.status, "status"), safe_description_code: typeof o.safe_description_code === "string" ? o.safe_description_code : null, reversal_of_reference: typeof o.reversal_of_reference === "string" ? o.reversal_of_reference : null, related_reference: typeof o.related_reference === "string" ? o.related_reference : null }; }
function validateCredit(v: unknown): CreditLot { const o = obj(v); return { credit_reference: str(o.credit_reference, "credit_reference"), bucket_type: str(o.bucket_type, "bucket_type"), original_amount_rial: o.original_amount_rial == null ? undefined : assertSafeRial(o.original_amount_rial, "original_amount_rial"), remaining_amount_rial: assertSafeRial(o.remaining_amount_rial, "remaining_amount_rial"), issued_at: optDate(o.issued_at, "issued_at"), expires_at: optDate(o.expires_at, "expires_at"), status: str(o.status, "status"), source_operation: typeof o.source_operation === "string" ? o.source_operation : null }; }
function validateReservation(v: unknown): Reservation { const o = obj(v); if (o.currency !== "IRR") throw new Error("invalid_currency"); return { reservation_reference: str(o.reservation_reference, "reservation_reference"), amount_rial: assertSafeRial(o.amount_rial, "amount_rial"), currency: "IRR", status: str(o.status, "status"), purpose_code: typeof o.purpose_code === "string" ? o.purpose_code : null, created_at: optDate(o.created_at, "created_at"), expires_at: date(o.expires_at, "expires_at"), released_at: optDate(o.released_at, "released_at"), captured_at: optDate(o.captured_at, "captured_at"), related_reference: typeof o.related_reference === "string" ? o.related_reference : null }; }
function page<T>(v: unknown, item: (x: unknown)=>T): Page<T> { const o = obj(v); return { items: Array.isArray(o.items) ? o.items.map(item) : [], next_cursor: typeof o.next_cursor === "string" ? o.next_cursor : null }; }
export const getWalletSummary = (signal?: AbortSignal) => dedupe("summary", () => json("", validateSummary, { signal }));
export const getWalletPolicy = (signal?: AbortSignal) => dedupe("policy", () => json("/policy", validatePolicy, { signal }));
export const listTransactions = (cursor?: string, signal?: AbortSignal) => json(`/transactions${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ""}`, (v) => page(v, validateTx), { signal });
export const getTransaction = (ref: string, signal?: AbortSignal) => json(`/transactions/${encodeURIComponent(ref)}`, validateTx, { signal });
export const listCredits = (signal?: AbortSignal) => json("/credits", (v) => page(v, validateCredit), { signal });
export const listReservations = (signal?: AbortSignal) => json("/reservations", (v) => page(v, validateReservation), { signal });
