"use client";
import React from "react";
import {Alert, AppShell, Badge, Button, Card, EmptyState, Field, Input, MobileNavigation, PageHeader, PasswordInput, Sidebar} from "@vpnsale/ui";

const customer=["نمای کلی","سرویس‌ها","سفارش‌ها","کیف پول","پشتیبانی","حساب"];
const reseller=["مشتریان مدیریت‌شده","سفارش‌های فروشندگی","فروش","کمیسیون‌ها","قیمت‌گذاری کاتالوگ","گزارش‌های فروشندگی"];
const admin=["مرکز فرمان","مشتریان","فروشندگان","سرویس و ارائه‌دهنده","فعالیت حسابرسی","سلامت سامانه"];
const links=(labels:string[])=>labels.map((label,index)=>({label,href:"#",current:index===0}));

export function DashboardPreview({role}:{role:"customer"|"reseller"|"admin"}):React.ReactElement {
 const items=role==="admin"?admin:role==="reseller"?[...customer,...reseller]:customer;
 const title=role==="admin"?"مرکز عملیات مدیریت":role==="reseller"?"کسب‌وکار فروشندگی من":"نمای کلی حساب من";
 return <AppShell density={role==="admin"?"compact":"comfortable"} sidebar={<Sidebar label="ناوبری اصلی" brand={<><strong>DR•PING</strong><p className="ui-muted">{role==="admin"?"کنسول امن مدیریت":"دسترسی یکپارچه مشتری"}</p></>} items={links(items)} footer={<Badge tone={role==="admin"?"warning":"info"}>{role==="admin"?"امنیت تقویت‌شده":role==="reseller"?"مشتری · فروشنده":"مشتری"}</Badge>}/>} mobileNavigation={<MobileNavigation label="ناوبری موبایل" items={links(items.slice(0,5))}/>}><PageHeader eyebrow={role==="admin"?"نشست مدیریت · تأیید دومرحله‌ای الزامی":"اطلاعات قطعی نمایشی"} title={title} actions={<Button variant="secondary">جستجو و فرمان</Button>}/>{role==="reseller"&&<Alert title="یک حساب، قابلیت‌های بیشتر" tone="info">قابلیت‌های مشتری حفظ شده‌اند و ابزارهای فروشندگی بر اساس نقش افزوده می‌شوند.</Alert>}<section className="preview-stats"><Card><span className="ui-muted">{role==="admin"?"وضعیت امنیت":"سرویس‌های فعال"}</span><strong className="ui-stat">{role==="admin"?"پایدار":"۲"}</strong></Card><Card><span className="ui-muted">{role==="reseller"?"فروش این ماه":role==="admin"?"رویدادهای حسابرسی":"سفارش در جریان"}</span><strong className="ui-stat">{role==="reseller"?"۱۸":role==="admin"?"۱۲":"۱"}</strong></Card><Card><span className="ui-muted">{role==="admin"?"سلامت ارائه‌دهندگان":"کیف پول"}</span><strong className="ui-stat">{role==="admin"?"بدون اختلال":"۸۴۰٬۰۰۰ ریال"}</strong></Card></section><section className="preview-grid"><Card><h2>{role==="admin"?"فعالیت حسابرسی":"آخرین فعالیت‌ها"}</h2><p className="ui-muted">رویدادهای حساس با زمان UTC و شناسه پیگیری نمایش داده می‌شوند.</p></Card><EmptyState title={role==="admin"?"هشدار عملیاتی وجود ندارد":"اقدام فوری ندارید"} description="این پیش‌نمایش هیچ عملیات نوشتنی اجرا نمی‌کند."/></section></AppShell>
}

export function AuthLayout({title,eyebrow="هویت یکپارچه DR•PING",children,admin=false}:{title:string;eyebrow?:string;children:React.ReactNode;admin?:boolean}) {return <main className={`auth-layout${admin?" auth-layout--admin":""}`}><section className="auth-brand"><strong>DR•PING</strong><p>{admin?"ورود مدیران مستقل از تلگرام و با کنترل دومرحله‌ای":"یک حساب امن برای وب و تلگرام"}</p></section><Card className="auth-card"><PageHeader eyebrow={eyebrow} title={title}/>{children}<small className="ui-muted">این صفحه صرفاً پیش‌نمایش است و هیچ درخواست احراز هویت ارسال نمی‌کند.</small></Card></main>}
const PreviewForm=({label,children}:{label:string;children:React.ReactNode})=><form aria-label={label} data-preview-form onSubmit={event=>event.preventDefault()}>{children}</form>;
export function SignInForm(){return <PreviewForm label="فرم ورود"><Field label="نام کاربری"><Input name="username" autoComplete="username" required/></Field><Field label="رمز عبور"><PasswordInput name="password" autoComplete="current-password" required/></Field><a href="/ui-preview/auth/forgot-password">رمز عبور را فراموش کرده‌ام</a><Alert title="زمینه تلگرام" tone="info">حضور در مینی‌اپ به معنی احراز هویت نیست؛ سرور باید داده آغازین را تأیید کند.</Alert><Button type="submit">ورود امن</Button></PreviewForm>}
export function RegistrationForm(){return <PreviewForm label="فرم ثبت‌نام"><Field label="نام کاربری"><Input name="username" autoComplete="username" required/></Field><Field label="رمز عبور"><PasswordInput name="password" autoComplete="new-password" required/></Field><Field label="تکرار رمز عبور"><PasswordInput name="password-confirmation" autoComplete="new-password" required/></Field><Field label="ایمیل (اختیاری)" hint="برای بازیابی حساب پیشنهاد می‌شود."><Input name="email" type="email" autoComplete="email"/></Field><Alert title="روش بازیابی را از دست ندهید" tone="warning">اگر ایمیل وارد نکنید، کدهای بازیابی را در محلی امن نگه دارید.</Alert><Button type="submit">ساخت حساب</Button></PreviewForm>}
const identifier=(kind:"email"|"code")=><PreviewForm label={kind==="email"?"فرم بازیابی ایمیل":"فرم کد بازیابی"}><Field label={kind==="email"?"ایمیل تأییدشده":"کد بازیابی"}><Input name={kind} type={kind==="email"?"email":"text"} autoComplete={kind==="email"?"email":"one-time-code"} inputMode={kind==="code"?"text":undefined} required/></Field><p className="ui-muted">پاسخ سامانه برای حساب موجود و ناموجود یکسان خواهد بود.</p><Button type="submit">ادامه امن</Button></PreviewForm>;
export function AuthComposition({screen}:{screen:string}):React.ReactElement {switch(screen){
 case"sign-in":return <AuthLayout title="ورود به حساب"><SignInForm/></AuthLayout>;
 case"register":return <AuthLayout title="ساخت حساب جدید"><RegistrationForm/></AuthLayout>;
 case"forgot-password":return <AuthLayout title="بازیابی رمز عبور"><PreviewForm label="فرم آغاز بازیابی"><Field label="نام کاربری"><Input autoComplete="username" required/></Field><Button>مشاهده روش‌های بازیابی</Button></PreviewForm></AuthLayout>;
 case"recovery-method":return <AuthLayout title="انتخاب روش بازیابی"><div className="auth-options"><Button variant="secondary">ایمیل تأییدشده</Button><Button variant="secondary">تلگرام متصل‌شده</Button><Button variant="secondary">کد بازیابی</Button></div><p className="ui-muted">فقط روش‌هایی که پیش‌تر برای حساب تأیید شده‌اند قابل استفاده‌اند.</p></AuthLayout>;
 case"recovery-email":return <AuthLayout title="بازیابی با ایمیل">{identifier("email")}</AuthLayout>;
 case"recovery-telegram":return <AuthLayout title="بازیابی با تلگرام"><Alert title="تلگرام متصل‌شده" tone="info">فقط شناسه عددی تلگرامی که قبلاً سمت سرور متصل و تأیید شده است پذیرفته می‌شود.</Alert><Button>ارسال درخواست عمومی</Button></AuthLayout>;
 case"recovery-code":return <AuthLayout title="بازیابی با کد">{identifier("code")}</AuthLayout>;
 case"reset-password":return <AuthLayout title="تنظیم رمز عبور تازه"><PreviewForm label="فرم تنظیم رمز"><Field label="رمز تازه"><PasswordInput autoComplete="new-password" required/></Field><Field label="تکرار رمز تازه"><PasswordInput autoComplete="new-password" required/></Field><Button>ذخیره رمز تازه</Button></PreviewForm></AuthLayout>;
 case"telegram-link":return <AuthLayout title="اتصال حساب تلگرام"><Alert title="تأیید سمت سرور" tone="warning">هویت تلگرام از مقادیر خوانده‌شده در مرورگر پذیرفته نمی‌شود.</Alert><Button>آغاز اتصال امن</Button></AuthLayout>;
 case"telegram-unlink":return <AuthLayout title="قطع اتصال تلگرام"><Alert title="تأیید اقدام حساس" tone="danger">پیش از قطع اتصال، وجود یک روش بازیابی جایگزین بررسی می‌شود.</Alert><div className="ui-actions"><Button variant="danger">قطع اتصال</Button><Button variant="secondary">انصراف</Button></div></AuthLayout>;
 case"devices":return <AuthLayout title="دستگاه‌های فعال"><Card><h2>مرورگر فعلی</h2><Badge tone="success">فعال</Badge><p className="ui-muted">آخرین فعالیت: اکنون · تهران</p></Card><Button variant="danger">خروج از دستگاه‌های دیگر</Button></AuthLayout>;
 case"admin-totp":return <AuthLayout title="تأیید دومرحله‌ای مدیر" admin><PreviewForm label="فرم کد یک‌بارمصرف مدیر"><Field label="کد برنامه تأییدکننده"><Input name="totp" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]*" required/></Field><Button>تأیید هویت مدیر</Button><a href="/ui-preview/auth/admin-recovery-codes">استفاده از کد بازیابی</a></PreviewForm></AuthLayout>;
 case"admin-recovery-codes":return <AuthLayout title="کدهای بازیابی مدیر" admin><Alert title="دسترسی اضطراری" tone="warning">هر کد یک‌بار مصرف است و استفاده از آن در حسابرسی ثبت می‌شود.</Alert>{identifier("code")}</AuthLayout>;
 default:return <AuthLayout title="صفحه پیدا نشد"><EmptyState title="پیش‌نمایش ناشناخته"/></AuthLayout>}}
