"use client";
import React from "react";
import { fa, formatDate } from "../i18n/fa";
import { listCategories, listProducts, getProduct, getProductOptions, createQuote, getQuote } from "../catalog/api";
import { defaultSelection, idempotencyKey, validateSelection } from "../catalog/builder";
import { normalizeComparison } from "../catalog/comparison";
import { formatDays, formatRial, formatTomanFromRial, formatTraffic, validateComponentSum } from "../catalog/format";
import { PreviewController } from "../catalog/preview-controller";
import type { Category, PricePreview, ProductDetail, ProductOptions, ProductSummary, Quote, QuoteSelection } from "../catalog/types";
function useCatalog(): { categories: Category[]; products: ProductSummary[]; error: string | null } { const [categories, setCategories] = React.useState<Category[]>([]); const [products, setProducts] = React.useState<ProductSummary[]>([]); const [error, setError] = React.useState<string | null>(null); React.useEffect(() => { const ac = new AbortController(); void Promise.all([listCategories("fa", ac.signal), listProducts("fa", ac.signal)]).then(([c, p]) => { setCategories(c); setProducts(p); }).catch((e: Error) => { if (e.name !== "AbortError") setError(e.message); }); return () => ac.abort(); }, []); return { categories, products, error }; }
export function Storefront(): React.ReactElement { const { categories, products, error } = useCatalog(); if (error) return <CatalogState code={error} />; return <section><h1>{fa.catalog.store}</h1><p>{fa.home.subtitle}</p><NavTiles /><h2>{fa.catalog.categories}</h2><div className="cards">{categories.map((c) => <a className="card" href={`/catalog/products?category=${c.id}`} key={c.id}><strong>{c.name ?? c.slug}</strong><span>{c.description}</span></a>)}</div><h2>{fa.catalog.products}</h2>{products.length ? <ProductGrid products={products} /> : <CatalogState code="empty" />}</section>; }
function NavTiles(): React.ReactElement { return <div className="actions"><a className="button" href="/catalog/categories">{fa.catalog.categories}</a><a className="button" href="/catalog/products">{fa.catalog.products}</a><a className="button" href="/catalog/compare">{fa.catalog.compare}</a></div>; }
export function CategoriesPage(): React.ReactElement { const { categories, error } = useCatalog(); if (error) return <CatalogState code={error} />; return <section><h1>{fa.catalog.categories}</h1><div className="cards">{categories.map((c) => <a className="card" href={`/catalog/products?category=${c.id}`} key={c.id}><strong>{c.name ?? c.slug}</strong><span dir="ltr">{c.slug}</span></a>)}</div></section>; }
export function ProductsPage(): React.ReactElement { const { products, error } = useCatalog(); const [q, setQ] = React.useState(""); if (error) return <CatalogState code={error} />; const filtered = products.filter((p) => `${p.name ?? ""} ${p.description ?? ""} ${p.machine_code}`.toLowerCase().includes(q.toLowerCase().slice(0, 80))); return <section><h1>{fa.catalog.products}</h1><label>{fa.catalog.search}<input value={q} maxLength={80} onChange={(e) => setQ(e.currentTarget.value)} /></label><button onClick={() => setQ("")}>{fa.catalog.clear}</button>{filtered.length ? <ProductGrid products={filtered} /> : <CatalogState code="empty" />}</section>; }
function ProductGrid({ products }: { products: ProductSummary[] }): React.ReactElement { return <div className="cards">{products.map((p) => <article className="card" key={p.id}><h3>{p.name ?? p.machine_code}</h3><p>{p.description}</p><span dir="ltr">{p.machine_code}</span><div className="actions"><a className="button" href={`/catalog/products/${p.id}`}>{fa.catalog.details}</a><a className="button" href={`/catalog/compare?ids=${p.id}`}>{fa.catalog.addCompare}</a></div></article>)}</div>; }
function useProduct(id: string): { product?: ProductDetail; options?: ProductOptions; error?: string } { const [state, setState] = React.useState<{ product?: ProductDetail; options?: ProductOptions; error?: string }>({}); React.useEffect(() => { const ac = new AbortController(); void Promise.all([getProduct(id, "fa", ac.signal), getProductOptions(id, ac.signal)]).then(([product, options]) => setState({ product, options })).catch((e: Error) => { if (e.name !== "AbortError") setState({ error: e.message }); }); return () => ac.abort(); }, [id]); return state; }
export function ProductPage({ productId }: { productId: string }): React.ReactElement { const { product, options, error } = useProduct(productId); if (error) return <CatalogState code={error} />; if (!product || !options) return <CatalogState code="loading" />; const route = options.product_type === "FIXED_PLAN" ? "fixed" : "custom"; return <section><h1>{product.name ?? product.machine_code}</h1><p>{product.description}</p><dl className="grid"><Field label="ID" value={product.id} ltr /><Field label="نوع" value={options.product_type} ltr /><Field label={fa.catalog.traffic} value={options.options.fixed_traffic_bytes ? formatTraffic(options.options.fixed_traffic_bytes) : `${formatTraffic(options.options.traffic.minimum)} - ${formatTraffic(options.options.traffic.maximum)}`} /><Field label={fa.catalog.duration} value={options.options.fixed_duration_days ? formatDays(options.options.fixed_duration_days) : `${formatDays(options.options.duration_days.minimum)} - ${formatDays(options.options.duration_days.maximum)}`} /></dl><div className="actions"><a className="button" href={`/catalog/products/${product.id}/${route}`}>{route === "fixed" ? fa.catalog.fixed : fa.catalog.custom}</a><a className="button" href={`/catalog/compare?ids=${product.id}`}>{fa.catalog.compare}</a><a className="button" href="/catalog/products">{fa.catalog.products}</a></div></section>; }
export function BuilderPage({ productId }: { productId: string }): React.ReactElement { const { product, options, error } = useProduct(productId); const [selection, setSelection] = React.useState<QuoteSelection | null>(null); const [preview, setPreview] = React.useState<PricePreview | null>(null); const [message, setMessage] = React.useState<string | null>(null); const controller = React.useMemo(() => new PreviewController(), []); React.useEffect(() => { if (options && !selection) setSelection(defaultSelection(productId, options)); }, [options, productId, selection]); React.useEffect(() => () => controller.cancel(), [controller]); if (error) return <CatalogState code={error} />; if (!product || !options || !selection) return <CatalogState code="loading" />; const errors = validateSelection(selection, options); const update = (patch: Partial<QuoteSelection>) => { setPreview(null); setSelection({ ...selection, ...patch }); }; const doPreview = async () => { if (errors.length) { setMessage(errors[0]?.message ?? ""); return; } setMessage("..."); try { const out = await controller.request(selection); setPreview(out); setMessage(fa.catalog.nonBinding); } catch (e) { setMessage(e instanceof Error ? e.message : "catalog_error"); } }; const doQuote = async () => { const q = await createQuote(selection, idempotencyKey()); location.href = `/catalog/quotes/${q.quote_reference}`; }; return <section><h1>{options.product_type === "FIXED_PLAN" ? fa.catalog.fixed : fa.catalog.custom}</h1><p>{product.name ?? product.machine_code}</p><div className="grid"><NumberInput label={fa.catalog.traffic} value={selection.traffic_bytes} disabled={Boolean(options.options.fixed_traffic_bytes)} onChange={(traffic_bytes) => update({ traffic_bytes })} /><NumberInput label={fa.catalog.duration} value={selection.duration_days} disabled={Boolean(options.options.fixed_duration_days)} onChange={(duration_days) => update({ duration_days })} /><NumberInput label={fa.catalog.devices} value={selection.device_count} disabled={Boolean(options.options.fixed_device_count)} onChange={(device_count) => update({ device_count })} /><Select label={fa.catalog.location} value={selection.location_code} options={options.options.location_options} onChange={(location_code) => update({ location_code })} /><Select label={fa.catalog.quality} value={selection.quality_code} options={options.options.quality_options} onChange={(quality_code) => update({ quality_code })} /></div>{errors.map((e) => <p className="danger-text" key={e.field}>{e.message}</p>)}<div className="actions"><button onClick={() => void doPreview()}>{fa.catalog.preview}</button><button disabled={!preview} onClick={() => void doQuote()}>{fa.catalog.quote}</button></div><div aria-live="polite">{message}</div>{preview ? <PriceBreakdown preview={preview} /> : null}</section>; }
function NumberInput({ label, value, disabled, onChange }: { label: string; value: number; disabled?: boolean; onChange: (v: number) => void }): React.ReactElement { return <label>{label}<input dir="ltr" type="number" value={value} disabled={disabled} onChange={(e) => onChange(Number(e.currentTarget.value))} /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: { code: string; enabled?: boolean }[]; onChange: (v: string) => void }): React.ReactElement { return <label>{label}<select dir="ltr" value={value} onChange={(e) => onChange(e.currentTarget.value)}>{options.map((o) => <option disabled={o.enabled === false} value={o.code} key={o.code}>{o.code}</option>)}</select></label>; }
function PriceBreakdown({ preview }: { preview: PricePreview | Quote }): React.ReactElement { const ok = validateComponentSum(preview.subtotal_minor, preview.components); return <section className="card"><h2>{fa.catalog.preview}</h2>{!ok ? <p className="danger-text">malformed_response</p> : null}<Field label="currency" value={preview.currency} ltr /><Field label="subtotal" value={`${formatRial(preview.subtotal_minor)} / ${formatTomanFromRial(preview.subtotal_minor)}`} ltr /><ul>{preview.components.map((c) => <li key={`${c.order}-${c.code}`}><span dir="ltr">{c.code}</span> — {c.label}: <b dir="ltr">{formatRial(c.amount_minor)}</b></li>)}</ul><Field label="final" value={`${formatRial(preview.final_amount_minor)} / ${formatTomanFromRial(preview.final_amount_minor)}`} ltr /><small>{"binding" in preview ? fa.catalog.nonBinding : fa.catalog.noCheckout}</small></section>; }
export function QuotePage({ reference }: { reference: string }): React.ReactElement { const [quote, setQuote] = React.useState<Quote | null>(null); const [error, setError] = React.useState<string | null>(null); React.useEffect(() => { const ac = new AbortController(); void getQuote(reference, ac.signal).then(setQuote).catch((e: Error) => setError(e.message)); return () => ac.abort(); }, [reference]); if (error) return <CatalogState code={error} />; if (!quote) return <CatalogState code="loading" />; const expired = quote.status !== "ACTIVE" || new Date(quote.expires_at).getTime() <= Date.now(); return <section><h1>پیش‌فاکتور</h1>{expired ? <p className="danger-text">{fa.catalog.expired}</p> : null}<Field label="reference" value={quote.quote_reference} ltr /><Field label="issued" value={formatDate(quote.issued_at)} ltr /><Field label="expires" value={formatDate(quote.expires_at)} ltr /><PriceBreakdown preview={quote} /><p>{fa.catalog.noCheckout}</p><a className="button" href={`/catalog/products/${quote.product_id}`}>{fa.catalog.recalc}</a></section>; }
export function ComparePage({ ids = "" }: { ids?: string }): React.ReactElement { const list = normalizeComparison(ids.split(",")); return <section><h1>{fa.catalog.compare}</h1><p>حداکثر سه محصول با داده واقعی کاتالوگ مقایسه می‌شوند.</p>{list.length ? <div className="cards">{list.map((id) => <ProductPage productId={id} key={id} />)}</div> : <CatalogState code="empty" />}</section>; }
function Field({ label, value, ltr = false }: { label: string; value: React.ReactNode; ltr?: boolean }): React.ReactElement { return <div className="field"><span>{label}</span><b dir={ltr ? "ltr" : "auto"}>{value}</b></div>; }
export function CatalogState({ code }: { code: string }): React.ReactElement { const text = code === "loading" ? fa.states.loading : code === "empty" ? fa.catalog.empty : code === "service_unavailable" ? fa.states.service : code === "rate_limited" ? fa.states.rate : code === "not_found" ? fa.states.notFound : fa.states.network; return <section className="state"><h1>{fa.catalog.store}</h1><p>{text}</p><button onClick={() => location.reload()}>{fa.actions.retry}</button></section>; }
