"use client";
import React from "react";
import { Alert, Avatar, Badge, Button, Card, PageHeader } from "@vpnsale/ui";
import { createTelegramWebApp, synchronizeTelegramCssVariables } from "@vpnsale/telegram-webapp";
import { loadCustomerConfig } from "../config/public-config";
import { fa, formatDate } from "../i18n/fa";
import { bootstrapCustomer, type BootstrapResult } from "../auth/bootstrap";
import { createTelegramLinkChallenge, enrollAccountCredentials, logout, revokeAllSessions, revokeOtherSessions, revokeSession, unlinkTelegram } from "../auth/api-client";
import type { AuthCapabilities, CustomerAuthState, CustomerProfile, CustomerSession } from "../auth/types";
import { createFakeTelegramAdapter, createTelegramAdapter, waitForTelegramBridge } from "../telegram/adapter";
import { BuilderPage, CategoriesPage, ComparePage, ProductPage, ProductsPage, QuotePage } from "./Catalog";
import { WalletShell } from "./Wallet";
import { OrderPayPage, PaymentDetailPage, PaymentReturnPage, PaymentsPage, WalletTopupPage } from "./Payments";
import { CheckoutPage, InvoiceDetailPage, InvoicesPage, OrderDetailPage, OrdersPage, OrderTimelinePage } from "./Commerce";
import { CustomerSupportHome } from "../support/Support";
import { accountNavigation, customerNavigation } from "./customer-navigation";
const emptyProfile: CustomerProfile = { customer_id: "—", account_status: "—", telegram_user_id: null, username: null, account_username: null, first_name: null, last_name: null, language_code: null, created_at: new Date(0).toISOString(), last_seen_at: null, current_session_id: "—" };
type CustomerPage = "home" | "profile" | "sessions" | "security" | "services" | "state" | "not-found" | "catalog-categories" | "catalog-products" | "catalog-product" | "catalog-fixed" | "catalog-custom" | "catalog-compare" | "catalog-quote" | "checkout" | "checkout-session" | "orders" | "order-detail" | "order-timeline" | "invoices" | "invoice-detail" | "wallet" | "wallet-top-up" | "wallet-transactions" | "wallet-transaction" | "wallet-credits" | "wallet-reservations" | "wallet-policy" | "payments" | "payment-detail" | "payment-return" | "order-pay" | "support";
export function CustomerApp({ page = "home", productId, quoteReference, orderReference, checkoutReference, invoiceReference, transactionReference, paymentReference, compareIds = "" }: { page?: CustomerPage; productId?: string; quoteReference?: string; orderReference?: string; checkoutReference?: string; invoiceReference?: string; transactionReference?: string; paymentReference?: string; compareIds?: string }): React.ReactElement { const config = loadCustomerConfig(); const [result, setResult] = React.useState<BootstrapResult>({ state: "INITIALIZING" }); const [theme, setTheme] = React.useState<"light" | "dark">("dark"); React.useEffect(() => { const controller = new AbortController(); const adapter = config.fakeTelegramEnabled ? createFakeTelegramAdapter(window.__VPN_SALE_FAKE_TELEGRAM_INIT_DATA__) : createTelegramAdapter(); const shared=createTelegramWebApp(); const synchronize=()=>{setTheme(shared.colorScheme());document.documentElement.dataset.theme=shared.colorScheme();document.documentElement.toggleAttribute("data-telegram-theme",shared.available())}; const stopCss=synchronizeTelegramCssVariables(document.documentElement,shared); const stopTheme=shared.onThemeChanged(synchronize); synchronize(); const offTheme = adapter.onThemeChanged(() => setTheme(adapter.getTheme().colorScheme === "dark" ? "dark" : "light")); void waitForTelegramBridge(adapter, controller.signal).then(() => bootstrapCustomer(adapter)).then((next) => { if (!controller.signal.aborted) setResult(next); }).catch(() => { if (!controller.signal.aborted) setResult({ state: "NETWORK_ERROR" }); }); return ()=>{controller.abort();offTheme();stopTheme();stopCss()}; }, [config.fakeTelegramEnabled]); const authenticated = result.state === "AUTHENTICATED"; const profile = result.profile ?? emptyProfile; return <main className="customer" data-theme={theme}>{authenticated ? <Shell page={page} productId={productId} quoteReference={quoteReference} orderReference={orderReference} checkoutReference={checkoutReference} invoiceReference={invoiceReference} transactionReference={transactionReference} paymentReference={paymentReference} compareIds={compareIds} profile={profile} sessions={result.sessions ?? []} capabilities={result.capabilities!} setResult={setResult} /> : <>{result.state === "TELEGRAM_UNAVAILABLE" && result.capabilities?.password_login ? <section className="state"><h1>ورود به DR•PING</h1><p>برای ادامه با حساب وب وارد شوید.</p><a className="ui-button" href="/auth/sign-in">ورود امن</a>{result.capabilities.public_registration ? <a className="ui-button ui-button--ghost" href="/auth/register">ثبت‌نام</a> : null}</section> : <StateScreen state={result.state} bot={config.botUsername} />}</>}</main>; }
function Shell({ page, productId, quoteReference, orderReference, checkoutReference, invoiceReference, transactionReference, paymentReference, compareIds, profile, sessions, capabilities, setResult }: { page: CustomerPage; productId?: string; quoteReference?: string; orderReference?: string; checkoutReference?: string; invoiceReference?: string; transactionReference?: string; paymentReference?: string; compareIds: string; profile: CustomerProfile; sessions: CustomerSession[]; capabilities: AuthCapabilities; setResult: (r: BootstrapResult) => void }): React.ReactElement {
  const primaryPage = page === "catalog-categories" || page.startsWith("catalog-") ? "catalog-products" : page === "services" ? "services" : page;
  const content = page === "profile" ? <Profile profile={profile} /> : page === "sessions" ? <Sessions sessions={sessions} setResult={setResult} /> : page === "security" ? <Security profile={profile} capabilities={capabilities} botUsername={loadCustomerConfig().botUsername} setResult={setResult} /> : page === "services" ? <section><h1>سرویس‌های من</h1><p className="ui-muted">وضعیت آماده‌سازی و تحویل فقط پس از تأیید سرویس نمایش داده می‌شود.</p></section> : page === "catalog-categories" ? <CategoriesPage /> : page === "catalog-products" ? <ProductsPage /> : page === "catalog-product" && productId ? <ProductPage productId={productId} /> : (page === "catalog-fixed" || page === "catalog-custom") && productId ? <BuilderPage productId={productId} /> : page === "catalog-compare" ? <ComparePage ids={compareIds} /> : page === "catalog-quote" && quoteReference ? <QuotePage reference={quoteReference} /> : page === "checkout" && quoteReference ? <CheckoutPage quoteReference={quoteReference} /> : page === "checkout-session" && checkoutReference ? <StateScreen state="SERVICE_UNAVAILABLE" /> : page === "orders" ? <OrdersPage /> : page === "order-detail" && orderReference ? <OrderDetailPage orderReference={orderReference} /> : page === "order-timeline" && orderReference ? <OrderTimelinePage orderReference={orderReference} /> : page === "invoices" ? <InvoicesPage /> : page === "invoice-detail" && invoiceReference ? <InvoiceDetailPage invoiceReference={invoiceReference} /> : page === "wallet" ? <WalletShell page="overview" /> : page === "wallet-top-up" ? <WalletTopupPage /> : page === "support" ? <CustomerSupportHome /> : page === "payments" ? <PaymentsPage /> : page === "payment-detail" && paymentReference ? <PaymentDetailPage reference={paymentReference} /> : page === "payment-return" ? <PaymentReturnPage /> : page === "order-pay" && orderReference ? <OrderPayPage orderReference={orderReference} /> : page === "wallet-transactions" ? <WalletShell page="transactions" /> : page === "wallet-transaction" && transactionReference ? <WalletShell page="transaction" transactionReference={transactionReference} /> : page === "wallet-credits" ? <WalletShell page="credits" /> : page === "wallet-reservations" ? <WalletShell page="reservations" /> : page === "wallet-policy" ? <WalletShell page="policy" /> : page === "not-found" ? <StateScreen state="UNAUTHORIZED" /> : <Home profile={profile} />;
  return <div className="customer-shell"><header className="customer-topbar"><a className="wordmark" href="/" aria-label="خانه DR.PING">DR.<span>PING</span></a><span className="beta-badge">نسخه آزمایشی</span><Avatar name={displayName(profile)} /></header><div className="customer-layout"><aside className="customer-sidebar"><nav aria-label="ناوبری مشتری">{customerNavigation.map(item => <a key={item.href} href={item.href} aria-current={primaryPage === item.page ? "page" : undefined}>{item.icon}<span>{item.label}</span></a>)}</nav></aside><div className="customer-content">{content}</div></div><nav className="customer-bottom-nav" aria-label="ناوبری اصلی مشتری">{customerNavigation.map(item => <a key={item.href} href={item.href} aria-current={primaryPage === item.page ? "page" : undefined}>{item.icon}<span>{item.label}</span></a>)}</nav></div>;
}
function displayName(profile: CustomerProfile): string { return [profile.first_name, profile.last_name].filter(Boolean).join(" ") || profile.account_username || profile.username || "مشتری"; }
function Identity({ profile }: { profile: CustomerProfile }): React.ReactElement { return <header className="identity"><Avatar name={displayName(profile)}/><div><strong>{displayName(profile)}</strong><Badge tone="success">{profile.account_status}</Badge></div></header>; }
const quickActions = [
  ["خرید سرویس", "/catalog/products", "M12 5v14M5 12h14"],
  ["سرویس‌های من", "/services", "M5 6h14v5H5zM5 15h14v3H5z"],
  ["افزایش موجودی", "/wallet/top-up", "M12 19V5m-5 5 5-5 5 5"],
  ["پشتیبانی", "/support", "M5 13v-1a7 7 0 0 1 14 0v1m-14 0v5h3v-5H5Zm14 0v5h-3v-5h3Z"],
] as const;
function Home({ profile }: { profile: CustomerProfile }): React.ReactElement { return <section className="customer-home"><header className="home-greeting"><div className="greeting-copy"><p>سلام، خوش آمدید</p><h1 title={displayName(profile)}>{displayName(profile)}</h1></div><span className="status-chip"><i />فعال</span></header><article className="service-empty"><div className="service-visual" aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M32 7 53 18v14c0 13-8.8 21-21 26C19.8 53 11 45 11 32V18L32 7Z"/><path d="m23 32 6 6 13-14"/></svg></div><div className="service-copy"><span className="eyebrow">وضعیت سرویس</span><h2>هنوز سرویس فعالی ندارید</h2><p>برای شروع، پلن مناسب خود را از فروشگاه انتخاب کنید.</p></div><a className="ui-button service-cta" href="/catalog/products">مشاهده پلن‌ها <span aria-hidden="true">←</span></a></article><section aria-labelledby="quick-title"><div className="section-heading"><h2 id="quick-title" className="section-title">دسترسی سریع</h2><span>میان‌برهای پرکاربرد</span></div><div className="quick-actions">{quickActions.map(([label,href,path])=><a href={href} key={href}><span className="quick-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d={path}/></svg></span><strong>{label}</strong><i aria-hidden="true">←</i></a>)}</div></section><article className="wallet-summary"><div className="wallet-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 7a3 3 0 0 1 3-3h11v16H6a2 2 0 0 1-2-2V7Zm0 1h14m-5 5h7v4h-7z"/></svg></div><div className="wallet-copy"><span>کیف پول</span><strong>موجودی و تراکنش‌ها، یک‌جا و در دسترس</strong><small>برای مشاهده جزئیات وارد کیف پول شوید.</small></div><a href="/wallet">مشاهده <span aria-hidden="true">←</span></a></article></section>; }
function Field({ label, value, ltr = false }: { label: string; value: React.ReactNode; ltr?: boolean }): React.ReactElement { return <div className="field"><span>{label}</span><b dir={ltr ? "ltr" : "auto"}>{value || fa.profile.empty}</b></div>; }
function Profile({ profile }: { profile: CustomerProfile }): React.ReactElement { return <div><h1>{fa.profile.title}</h1><nav className="account-navigation" aria-label="تنظیمات حساب">{accountNavigation.map(item => <a href={item.href} key={item.href}>{item.label}</a>)}<button type="button" onClick={() => void logout().then(() => location.reload())}>{fa.actions.logout}</button></nav><div className="grid"><Field label={fa.profile.customerId} value={profile.customer_id} ltr /><Field label="نام کاربری حساب" value={profile.account_username} ltr /><Field label={fa.profile.telegramId} value={profile.telegram_user_id} ltr /><Field label="نام کاربری تلگرام" value={profile.username ? `@${profile.username}` : null} ltr /><Field label={fa.profile.firstName} value={profile.first_name} /><Field label={fa.profile.lastName} value={profile.last_name} /><Field label={fa.profile.language} value={profile.language_code} ltr /><Field label={fa.profile.status} value={profile.account_status} /><Field label={fa.profile.created} value={formatDate(profile.created_at)} ltr /><Field label={fa.profile.lastSeen} value={formatDate(profile.last_seen_at)} ltr /><Field label={fa.profile.currentSession} value={profile.current_session_id} ltr /></div></div>; }
function Sessions({ sessions, setResult }: { sessions: CustomerSession[]; setResult: (r: BootstrapResult) => void }): React.ReactElement { return <div><h1>{fa.sessions.title}</h1><div className="actions"><button onClick={() => confirm(fa.actions.revokeOthers) && void revokeOtherSessions()}>{fa.actions.revokeOthers}</button><button className="danger" onClick={() => confirm(fa.actions.revokeAll) && void revokeAllSessions().then(() => setResult({ state: "EXPIRED" }))}>{fa.actions.revokeAll}</button></div>{sessions.length === 0 ? <p>{fa.profile.empty}</p> : sessions.map((s) => <article className="session" key={s.session_id}><h2>{s.device_label ?? fa.sessions.device} {s.current ? <span>{fa.sessions.current}</span> : null}</h2><Field label="ID" value={s.session_id} ltr /><Field label={fa.sessions.created} value={formatDate(s.created_at)} ltr /><Field label={fa.sessions.lastActive} value={formatDate(s.last_used_at)} ltr /><Field label={fa.sessions.idle} value={formatDate(s.idle_expires_at)} ltr /><Field label={fa.sessions.absolute} value={formatDate(s.absolute_expires_at)} ltr /><Field label={fa.sessions.revoked} value={s.revoked ? "بله" : "خیر"} />{!s.current && !s.revoked ? <button onClick={() => confirm(fa.actions.revoke) && void revokeSession(s.session_id)}>{fa.actions.revoke}</button> : null}</article>)}</div>; }
function Security({ profile, capabilities, botUsername, setResult }: { profile: CustomerProfile; capabilities: AuthCapabilities; botUsername: string | null; setResult: (r: BootstrapResult) => void }): React.ReactElement {
  const [password, setPassword] = React.useState(""); const [username, setUsername] = React.useState(""); const [confirmation, setConfirmation] = React.useState(""); const [challenge, setChallenge] = React.useState<{ value: string; expires: string } | null>(null); const [message, setMessage] = React.useState<string | null>(null); const linked = profile.telegram_user_id !== null; const telegram = createTelegramWebApp();
  const createLink = async (event: React.FormEvent) => { event.preventDefault(); setMessage(null); try { const result = await createTelegramLinkChallenge(password); setPassword(""); setChallenge({ value: result.challenge, expires: result.expires_at }); } catch { setMessage("درخواست انجام نشد. وضعیت حساب یا گذرواژه را بررسی کنید."); } };
  const enroll = async (event: React.FormEvent) => { event.preventDefault(); if (password !== confirmation) { setMessage("تکرار گذرواژه یکسان نیست."); return; } try { await enrollAccountCredentials(username, password, telegram.rawInitData()); setPassword(""); setConfirmation(""); location.reload(); } catch { setMessage("ثبت اطلاعات انجام نشد. نام دیگری انتخاب و دوباره تلاش کنید."); } };
  const unlink = async (event: React.FormEvent) => { event.preventDefault(); if (!confirm("همه نشست‌ها خارج می‌شوند. اتصال تلگرام قطع شود؟")) return; try { await unlinkTelegram(password); setResult({ state: "EXPIRED" }); } catch { setMessage("قطع اتصال انجام نشد."); } };
  return <div><PageHeader title="امنیت حساب یکپارچه" /><div className="grid"><Field label="تلگرام" value={linked ? "متصل" : "متصل نیست"} /><Field label="نام کاربری حساب" value={profile.account_username ?? "ثبت نشده"} /><Field label="ورود با گذرواژه" value={capabilities.password_login ? "فعال" : "غیرفعال"} />{linked && <Field label="نام نمایشی تلگرام" value={profile.username ? `@${profile.username}` : "بدون نام کاربری"} ltr />}</div>{message && <Alert title="نتیجه عملیات" tone="danger">{message}</Alert>}{!capabilities.telegram_linking && <Alert title="اتصال تلگرام در دسترس نیست" tone="warning">این قابلیت در حال حاضر غیرفعال است.</Alert>}{!linked && profile.account_username && capabilities.telegram_linking ? <form className="stack" onSubmit={createLink}><h2>اتصال تلگرام</h2><label className="field">گذرواژه فعلی<input required type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><Button type="submit">ساخت درخواست ده‌دقیقه‌ای</Button>{challenge && <Alert title="درخواست آماده است" tone="warning">تا {formatDate(challenge.expires)} معتبر است. این صفحه را باز نگه دارید.</Alert>}{challenge && botUsername ? <a className="ui-button" href={`https://t.me/${botUsername}?startapp=${encodeURIComponent(challenge.value)}`}>باز کردن تلگرام</a> : null}</form> : null}{linked && !profile.account_username && !capabilities.web_credential_enrollment && <Alert title="ساخت ورود وب در دسترس نیست" tone="warning">این قابلیت در حال حاضر غیرفعال است.</Alert>}{linked && !profile.account_username && capabilities.web_credential_enrollment ? <form className="stack" onSubmit={enroll}><h2>ساخت ورود وب</h2><label className="field">نام کاربری<input required dir="ltr" autoComplete="username" value={username} onChange={(e) => setUsername(e.target.value)} /></label><label className="field">گذرواژه<input required minLength={12} type="password" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><label className="field">تکرار گذرواژه<input required minLength={12} type="password" autoComplete="new-password" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /></label><p>حداقل ۱۲ نویسه؛ از نام کاربری و گذرواژه‌های رایج استفاده نکنید.</p><Button type="submit">ثبت ورود وب روی همین حساب</Button></form> : null}{linked && profile.account_username && capabilities.telegram_linking && capabilities.password_login ? <form className="stack" onSubmit={unlink}><h2>قطع اتصال تلگرام</h2><Alert title="هشدار" tone="warning">با قطع اتصال، همه نشست‌ها از جمله این دستگاه خارج می‌شوند. داده‌های حساب حذف نمی‌شوند.</Alert><label className="field">گذرواژه فعلی<input required type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><Button type="submit" variant="danger">قطع اتصال و خروج همه نشست‌ها</Button></form> : null}</div>;
}
function StateScreen({ state, bot }: { state: CustomerAuthState; bot?: string | null }): React.ReactElement { const text = state === "INITIALIZING" ? fa.states.loading : state === "TELEGRAM_UNAVAILABLE" ? fa.states.browser : state === "UNSUPPORTED_CLIENT" ? fa.states.unsupported : state === "EXPIRED" ? fa.states.expired : state === "BLOCKED" ? fa.states.blocked : state === "SUSPENDED" ? fa.states.suspended : state === "DEACTIVATED" ? fa.states.deactivated : state === "RATE_LIMITED" ? fa.states.rate : state === "SERVICE_UNAVAILABLE" ? fa.states.service : state === "NETWORK_ERROR" ? fa.states.network : fa.states.unauthorized; if(state==="INITIALIZING")return <section className="loading-dashboard" aria-label={text}><span className="skeleton-line"/><span className="skeleton-card"/><span className="skeleton-grid"/><span className="skeleton-card short"/></section>;return <section className="state"><span className="state-icon" aria-hidden="true">!</span><h1>{state === "NETWORK_ERROR" ? "ارتباط برقرار نشد" : state === "TELEGRAM_UNAVAILABLE" ? "تلگرام در دسترس نیست" : "وضعیت دسترسی"}</h1><p>{text}</p><div className="state-actions">{bot ? <a className="ui-button" href={`https://t.me/${bot}`}>{fa.actions.openTelegram}</a> : null}<Button onClick={() => location.reload()}>{fa.actions.retry}</Button></div></section>; }
