"use client";
import React from "react";
import { tokens } from "@vpnsale/ui";
import { loadCustomerConfig } from "../config/public-config";
import { fa, formatDate } from "../i18n/fa";
import { bootstrapCustomer, type BootstrapResult } from "../auth/bootstrap";
import { logout, revokeAllSessions, revokeOtherSessions, revokeSession } from "../auth/api-client";
import type { CustomerAuthState, CustomerProfile, CustomerSession } from "../auth/types";
import { createFakeTelegramAdapter, createTelegramAdapter } from "../telegram/adapter";
const emptyProfile: CustomerProfile = { customer_id: "—", account_status: "—", telegram_user_id: null, username: null, first_name: null, last_name: null, language_code: null, created_at: new Date(0).toISOString(), last_seen_at: null, current_session_id: "—" };
export function CustomerApp({ page = "home" }: { page?: "home" | "profile" | "sessions" | "security" | "state" | "not-found" }): React.ReactElement { const config = loadCustomerConfig(); const [result, setResult] = React.useState<BootstrapResult>({ state: "INITIALIZING" }); const [theme, setTheme] = React.useState<"light" | "dark">("light"); React.useEffect(() => { const adapter = config.fakeTelegramEnabled ? createFakeTelegramAdapter(window.__VPN_SALE_FAKE_TELEGRAM_INIT_DATA__) : createTelegramAdapter(); const offTheme = adapter.onThemeChanged(() => setTheme(adapter.getTheme().colorScheme === "dark" ? "dark" : "light")); document.documentElement.style.setProperty("--safe-bottom", `${adapter.getViewport().safeAreaInsetBottom ?? 0}px`); void bootstrapCustomer(adapter).then(setResult).catch(() => setResult({ state: "NETWORK_ERROR" })); return offTheme; }, [config.fakeTelegramEnabled]); const authenticated = result.state === "AUTHENTICATED"; const profile = result.profile ?? emptyProfile; return <main className={`customer ${theme}`}><style>{styles}</style>{authenticated ? <Shell page={page} profile={profile} sessions={result.sessions ?? []} setResult={setResult} /> : <StateScreen state={result.state} bot={config.botUsername} />}</main>; }
function Shell({ page, profile, sessions, setResult }: { page: string; profile: CustomerProfile; sessions: CustomerSession[]; setResult: (r: BootstrapResult) => void }): React.ReactElement { return <div className="shell"><aside className="side"><Identity profile={profile} /><Nav /><button className="ghost" onClick={() => void logout().then(() => setResult({ state: "UNAUTHORIZED" }))}>{fa.actions.logout}</button></aside><section className="panel">{page === "profile" ? <Profile profile={profile} /> : page === "sessions" ? <Sessions sessions={sessions} setResult={setResult} /> : page === "security" ? <Security /> : page === "not-found" ? <StateScreen state="UNAUTHORIZED" /> : <Home profile={profile} />}</section><nav className="bottom"><Nav /></nav></div>; }
function Identity({ profile }: { profile: CustomerProfile }): React.ReactElement { const name = [profile.first_name, profile.last_name].filter(Boolean).join(" ") || profile.username || "مشتری"; return <header className="identity"><div className="avatar">{name.slice(0, 1)}</div><div><strong>{name}</strong><span className="status">{profile.account_status}</span></div></header>; }
function Nav(): React.ReactElement { return <div className="nav"><a href="/">{fa.nav.home}</a><a href="/profile">{fa.nav.profile}</a><a href="/sessions">{fa.nav.sessions}</a><a href="/security">{fa.nav.security}</a></div>; }
function Home({ profile }: { profile: CustomerProfile }): React.ReactElement { return <div><h1>{fa.home.title}</h1><p>{fa.home.subtitle}</p><Identity profile={profile} /><div className="card disabled">{fa.home.coming}</div></div>; }
function Field({ label, value, ltr = false }: { label: string; value: React.ReactNode; ltr?: boolean }): React.ReactElement { return <div className="field"><span>{label}</span><b dir={ltr ? "ltr" : "auto"}>{value || fa.profile.empty}</b></div>; }
function Profile({ profile }: { profile: CustomerProfile }): React.ReactElement { return <div><h1>{fa.profile.title}</h1><div className="grid"><Field label={fa.profile.customerId} value={profile.customer_id} ltr /><Field label={fa.profile.telegramId} value={profile.telegram_user_id} ltr /><Field label={fa.profile.username} value={profile.username ? `@${profile.username}` : null} ltr /><Field label={fa.profile.firstName} value={profile.first_name} /><Field label={fa.profile.lastName} value={profile.last_name} /><Field label={fa.profile.language} value={profile.language_code} ltr /><Field label={fa.profile.status} value={profile.account_status} /><Field label={fa.profile.created} value={formatDate(profile.created_at)} ltr /><Field label={fa.profile.lastSeen} value={formatDate(profile.last_seen_at)} ltr /><Field label={fa.profile.currentSession} value={profile.current_session_id} ltr /></div></div>; }
function Sessions({ sessions, setResult }: { sessions: CustomerSession[]; setResult: (r: BootstrapResult) => void }): React.ReactElement { return <div><h1>{fa.sessions.title}</h1><div className="actions"><button onClick={() => confirm(fa.actions.revokeOthers) && void revokeOtherSessions()}>{fa.actions.revokeOthers}</button><button className="danger" onClick={() => confirm(fa.actions.revokeAll) && void revokeAllSessions().then(() => setResult({ state: "EXPIRED" }))}>{fa.actions.revokeAll}</button></div>{sessions.length === 0 ? <p>{fa.profile.empty}</p> : sessions.map((s) => <article className="session" key={s.session_id}><h2>{s.device_label ?? fa.sessions.device} {s.current ? <span>{fa.sessions.current}</span> : null}</h2><Field label="ID" value={s.session_id} ltr /><Field label={fa.sessions.created} value={formatDate(s.created_at)} ltr /><Field label={fa.sessions.lastActive} value={formatDate(s.last_used_at)} ltr /><Field label={fa.sessions.idle} value={formatDate(s.idle_expires_at)} ltr /><Field label={fa.sessions.absolute} value={formatDate(s.absolute_expires_at)} ltr /><Field label={fa.sessions.revoked} value={s.revoked ? "بله" : "خیر"} />{!s.current && !s.revoked ? <button onClick={() => confirm(fa.actions.revoke) && void revokeSession(s.session_id)}>{fa.actions.revoke}</button> : null}</article>)}</div>; }
function Security(): React.ReactElement { return <div><h1>{fa.security.title}</h1><p>{fa.security.body}</p><ul><li>Authorization header برای access token</li><li>credentials: include برای refresh cookie</li><li>CSRF برای عملیات cookie-authenticated</li></ul></div>; }
function StateScreen({ state, bot }: { state: CustomerAuthState; bot?: string | null }): React.ReactElement { const text = state === "INITIALIZING" ? fa.states.loading : state === "TELEGRAM_UNAVAILABLE" ? fa.states.browser : state === "UNSUPPORTED_CLIENT" ? fa.states.unsupported : state === "EXPIRED" ? fa.states.expired : state === "BLOCKED" ? fa.states.blocked : state === "SUSPENDED" ? fa.states.suspended : state === "DEACTIVATED" ? fa.states.deactivated : state === "RATE_LIMITED" ? fa.states.rate : state === "SERVICE_UNAVAILABLE" ? fa.states.service : state === "NETWORK_ERROR" ? fa.states.network : fa.states.unauthorized; return <section className="state"><h1>{fa.home.title}</h1><p>{text}</p>{bot ? <a className="button" href={`https://t.me/${bot}`}>{fa.actions.openTelegram}</a> : <small>نام عمومی ربات هنوز تنظیم نشده است.</small>}<button onClick={() => location.reload()}>{fa.actions.retry}</button></section>; }
const styles = `:root{--safe-bottom:0px}.customer{min-height:100vh;background:${tokens.color.bg};color:#172033;font-family:system-ui;padding:16px;padding-bottom:calc(16px + var(--safe-bottom))}.customer.dark{background:${tokens.color.darkBg};color:#f8fafc}.shell{display:grid;grid-template-columns:280px 1fr;gap:18px;max-width:1180px;margin:auto}.side,.panel,.state,.card,.session{background:rgba(255,255,255,.9);border:1px solid #dbe3ef;border-radius:${tokens.radius.card};padding:20px;box-shadow:0 18px 60px rgba(15,23,42,.08)}.dark .side,.dark .panel,.dark .state,.dark .card,.dark .session{background:#111827;border-color:#334155}.identity{display:flex;gap:12px;align-items:center}.avatar{width:44px;height:44px;border-radius:16px;background:${tokens.color.brand};color:white;display:grid;place-items:center}.status{display:block;color:#64748b}.nav{display:flex;flex-direction:column;gap:8px;margin:18px 0}.nav a,.button,button{border:0;border-radius:14px;padding:10px 14px;background:#e8eeff;color:#1638a6;text-decoration:none;cursor:pointer}.ghost{background:#eef2f7}.danger{background:#fee2e2;color:#991b1b}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.field{display:flex;flex-direction:column;gap:4px;padding:12px;border-radius:14px;background:rgba(148,163,184,.12)}.field span{color:#64748b}.session{margin-top:12px}.session h2{display:flex;justify-content:space-between}.actions{display:flex;gap:10px;flex-wrap:wrap}.disabled{opacity:.7}.bottom{display:none}@media(max-width:760px){.shell{display:block}.side{margin-bottom:12px}.side .nav{display:none}.bottom{display:block;position:fixed;inset:auto 10px calc(8px + var(--safe-bottom)) 10px}.bottom .nav{flex-direction:row;justify-content:space-around;background:#fff;border-radius:18px;padding:8px}.panel{margin-bottom:90px}}:focus-visible{outline:3px solid #f59e0b;outline-offset:2px}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}`;
