"use client";
import React from "react";
import { getInvoice, getOrder } from "../commerce/api";
import type { Invoice, Order } from "../commerce/types";
import { getWalletPolicy, getWalletSummary } from "../wallet/api";
import type { WalletPolicy, WalletSummary } from "../wallet/types";
import { createOrderPaymentIntent, createWalletTopupIntent, getPaymentIntent, listPaymentIntents, listPaymentMethods } from "../payments/api";
import { formatRial, formatTomanFromRial, parseRialInput, purposeLabel, statusLabel } from "../payments/format";
import { PaymentOperationController } from "../payments/idempotency";
import { validateRedirectAction } from "../payments/redirect";
import type { PaymentAction, PaymentIntent, PaymentMethod, PaymentPurpose } from "../payments/types";
type Load<T>={loading:boolean;data?:T;error?:string};
function useLoad<T>(loader:(signal:AbortSignal)=>Promise<T>, deps:React.DependencyList=[]):[Load<T>,()=>void]{const[t,setT]=React.useState(0);const[s,setS]=React.useState<Load<T>>({loading:true});React.useEffect(()=>{const c=new AbortController();setS({loading:true});loader(c.signal).then(data=>setS({loading:false,data})).catch(e=>{if(!c.signal.aborted)setS({loading:false,error:typeof e?.code==="string"?e.code:e instanceof Error?e.message:"PAYMENT_ERROR"})});return()=>c.abort();},[t,...deps]);return[s,()=>setT(x=>x+1)];}
function ErrorBox({code,onRetry}:{code?:string;onRetry?:()=>void}){return <section className="payment-state error"><h2>نمایش امن پرداخت ممکن نیست</h2><p>{code === "SERVICE_UNAVAILABLE" ? "سرویس پرداخت موقتاً در دسترس نیست." : code === "AUTHENTICATION_REQUIRED" ? "برای پرداخت ورود لازم است." : "پاسخ پرداخت معتبر یا قابل نمایش نیست."}</p><code>{code??"UNKNOWN"}</code>{onRetry?<button onClick={onRetry}>تلاش دوباره</button>:null}</section>}
function Money({value}:{value:number}){return <span className="money"><b>{formatRial(value)}</b><small>{formatTomanFromRial(value)}</small></span>}
function MethodCards({purpose,selected,onSelect}:{purpose:PaymentPurpose;selected?:string;onSelect:(m:PaymentMethod)=>void}){const[methods,reload]=useLoad(s=>listPaymentMethods(purpose,s),[purpose]);if(methods.error)return <ErrorBox code={methods.error} onRetry={reload}/>;if(methods.loading||!methods.data)return <div className="payment-skeleton">در حال دریافت روش‌های پرداخت…</div>;const visible=methods.data.filter(m=>m.supported_purposes.includes(purpose)&&!m.maintenance_mode);if(visible.length===0)return <section className="payment-state warn"><h2>روش پرداخت فعالی موجود نیست</h2><p>فقط روش‌های فعال و قابل نمایش مشتری از backend نشان داده می‌شوند؛ گزینه جعلی یا کارت‌به‌کارت اضافه نشده است.</p></section>;return <div className="payment-methods" role="radiogroup" aria-label="روش پرداخت">{visible.map(m=><button key={m.code} className={`payment-method ${selected===m.code?"selected":""}`} role="radio" aria-checked={selected===m.code} onClick={()=>onSelect(m)}><strong>{m.display_name??"روش پرداخت"}</strong><span>{m.description??"انتقال امن از مسیر اعلام‌شده توسط سرور"}</span><small>{m.method_kind} · {m.currency}</small>{m.min_amount_rial?<small>حداقل: {formatRial(m.min_amount_rial)}</small>:null}{m.max_amount_rial?<small>حداکثر: {formatRial(m.max_amount_rial)}</small>:null}</button>)}</div>}
function RedirectBox({action}:{action:PaymentAction}){const[url,setUrl]=React.useState<URL|null>(null);const[err,setErr]=React.useState<string|null>(null);React.useEffect(()=>{try{setUrl(validateRedirectAction(action));}catch(e){setErr(e instanceof Error?e.message:"unsafe_redirect")}},[action]);if(err)return <ErrorBox code={err}/>;return <section className="payment-state"><h2>آماده انتقال به درگاه</h2><p>نشانی درگاه فقط از پاسخ backend دریافت و از نظر پروتکل/میزبان بررسی شد. مرورگر پس از بازگشت، موفقیت را اثبات نمی‌کند.</p><a className="button" href={url?.toString()} rel="noreferrer">انتقال به درگاه</a></section>}
export function WalletTopupPage():React.ReactElement{const[wallet,reloadWallet]=useLoad(async s=>({summary:await getWalletSummary(s),policy:await getWalletPolicy(s)}));const[amount,setAmount]=React.useState("");const[method,setMethod]=React.useState<PaymentMethod>();const[review,setReview]=React.useState(false);const[action,setAction]=React.useState<PaymentAction>();const[busy,setBusy]=React.useState(false);const op=React.useRef(new PaymentOperationController()).current;if(wallet.error)return <ErrorBox code={wallet.error} onRetry={reloadWallet}/>;if(wallet.loading||!wallet.data)return <div className="payment-skeleton">در حال دریافت سیاست کیف پول…</div>;const parsed=(()=>{try{return parseRialInput(amount)}catch{return null}})();const p=wallet.data.policy;const s=wallet.data.summary;const validation=parsed==null?"مبلغ باید عدد صحیح ریال باشد.":parsed<p.minimum_topup_amount_rial?"کمتر از حداقل شارژ است.":parsed>p.maximum_topup_amount_rial?"بیشتر از حداکثر شارژ است.":p.maximum_wallet_balance_rial&&s.available_balance_rial+parsed>p.maximum_wallet_balance_rial?"از سقف موجودی کیف پول بیشتر می‌شود.":null;async function submit(){if(!parsed||!method||validation)return;setBusy(true);try{setAction(await createWalletTopupIntent(parsed,method.code,op.current()));}catch{setReview(false)}finally{setBusy(false)}} if(action)return <RedirectBox action={action}/>;return <div><h1>شارژ کیف پول</h1><section className="payment-grid"><article><h2>موجودی فعلی</h2><Money value={s.available_balance_rial}/><small>رزروشده: {formatRial(s.reserved_balance_rial)} · ثبت‌شده: {formatRial(s.posted_balance_rial)}</small></article><article><h2>سیاست شارژ</h2><p>حداقل {formatRial(p.minimum_topup_amount_rial)}</p><p>حداکثر {formatRial(p.maximum_topup_amount_rial)}</p>{p.maximum_wallet_balance_rial?<p>سقف کیف پول {formatRial(p.maximum_wallet_balance_rial)}</p>:null}</article></section><label>مبلغ به ریال<input inputMode="numeric" pattern="[0-9]*" value={amount} onChange={e=>{setAmount(e.currentTarget.value);setReview(false)}} aria-describedby="amount-help"/></label><small id="amount-help">تومان فقط نمایش مشتق‌شده است؛ ارسال به backend فقط با ریال انجام می‌شود.</small>{parsed!=null?<p><Money value={parsed}/></p>:null}{validation?<p className="danger-text">{validation}</p>:null}<MethodCards purpose="WALLET_TOPUP" selected={method?.code} onSelect={setMethod}/>{review&&parsed&&method&&!validation?<section className="payment-review"><h2>بازبینی شارژ</h2><p>مبلغ: <Money value={parsed}/></p><p>روش: {method.display_name??method.method_kind}</p><p>موجودی تخمینی غیرقطعی: {formatRial(s.available_balance_rial+parsed)}</p><button disabled={busy} onClick={()=>void submit()}>{busy?"در حال ایجاد…":"ایجاد درخواست پرداخت"}</button></section>:<button disabled={Boolean(validation)||!method} onClick={()=>setReview(true)}>ادامه و بازبینی</button>}</div>}
function IntentCard({intent}:{intent:PaymentIntent}){return <a className="payment-row" href={`/payments/${encodeURIComponent(intent.reference)}`}><code>{intent.reference}</code><span>{purposeLabel(intent.purpose)}</span>{intent.amount_rial!=null?<Money value={intent.amount_rial}/>:null}<b>{statusLabel(intent.status)}</b></a>}
export function PaymentsPage():React.ReactElement{const[list,reload]=useLoad(s=>listPaymentIntents(undefined,s));if(list.error)return <ErrorBox code={list.error} onRetry={reload}/>;return <div><h1>پرداخت‌های من</h1><a className="button" href="/wallet/top-up">شارژ کیف پول</a>{list.loading?<p>در حال دریافت تاریخچه…</p>:list.data?.items.length?list.data.items.map(i=><IntentCard key={i.reference} intent={i}/>):<section className="payment-state"><h2>هنوز پرداختی ثبت نشده است</h2><p>تاریخچه به‌صورت صفحه‌بندی‌شده از backend خوانده می‌شود و در مرورگر ذخیره نمی‌شود.</p></section>}</div>}
export function PaymentDetailPage({reference}:{reference:string}):React.ReactElement{const[detail,reload]=useLoad(s=>getPaymentIntent(reference,s),[reference]);if(detail.error)return <ErrorBox code={detail.error} onRetry={reload}/>;if(detail.loading||!detail.data)return <p>در حال دریافت پرداخت…</p>;const i=detail.data;return <div><h1>جزئیات پرداخت</h1><section className="payment-review"><p><code>{i.reference}</code></p><p>{purposeLabel(i.purpose)} · {statusLabel(i.status)}</p>{i.amount_rial!=null?<Money value={i.amount_rial}/>:null}<p>موفقیت فقط پس از وضعیت تأییدشده backend نمایش داده می‌شود.</p>{i.status==="RECONCILIATION_REQUIRED"?<p className="danger-text">این پرداخت نیازمند بررسی مالی است و موفق یا ناموفق قطعی نمایش داده نمی‌شود.</p>:null}{i.order_reference?<p>سفارش <code>{i.order_reference}</code></p>:null}{i.invoice_reference?<p>فاکتور <code>{i.invoice_reference}</code></p>:null}{i.wallet_transaction_reference?<p>تراکنش کیف پول <code>{i.wallet_transaction_reference}</code></p>:null}<button onClick={reload}>بررسی وضعیت</button></section></div>}
export function PaymentReturnPage():React.ReactElement{const params=new URLSearchParams(globalThis.location?.search??"");const ref=params.get("payment_reference")??params.get("reference")??"";return <div><h1>بازگشت از پرداخت</h1><p>پارامترهای مرورگر اثبات پرداخت نیستند؛ حتی success=true نادیده گرفته می‌شود.</p>{ref?<PaymentDetailPage reference={ref}/>:<ErrorBox code="missing_payment_reference"/>}</div>}
export function OrderPayPage({orderReference}:{orderReference:string}):React.ReactElement{const[data,reload]=useLoad(async s=>{const order=await getOrder(orderReference,s);const invoice=order.invoice_reference?await getInvoice(order.invoice_reference,s):undefined;return {order,invoice};},[orderReference]);const[method,setMethod]=React.useState<PaymentMethod>();const[action,setAction]=React.useState<PaymentAction>();const[busy,setBusy]=React.useState(false);const op=React.useRef(new PaymentOperationController()).current;if(data.error)return <ErrorBox code={data.error} onRetry={reload}/>;if(data.loading||!data.data)return <p>در حال دریافت سفارش…</p>;const order:Order=data.data.order;const invoice:Invoice|undefined=data.data.invoice;const payable=invoice&&invoice.status==="ISSUED"&&order.financial_status!=="PAID"&&order.status!=="CANCELLED";async function submit(){if(!method||!payable)return;setBusy(true);try{setAction(await createOrderPaymentIntent(orderReference,method.code,op.current()))}finally{setBusy(false)}}if(action)return <RedirectBox action={action}/>;return <div><h1>پرداخت سفارش</h1><section className="payment-review"><p>سفارش <code>{order.order_reference}</code></p>{invoice?<><p>فاکتور <code>{invoice.invoice_reference}</code></p><Money value={invoice.payable_total_rial}/></>:<p>فاکتور قابل پرداخت یافت نشد.</p>}<p>مبلغ فاکتور غیرقابل ویرایش و فقط از backend خوانده می‌شود.</p><p>{order.fulfillment_status==="READY_FOR_FULFILLMENT"?"پرداخت تکمیل‌شده به معنی تحویل سرویس نیست؛ سفارش برای ایجاد سرویس آینده در صف است.":"هیچ سرویس، QR یا لینک پیکربندی نمایش داده نمی‌شود."}</p></section>{!payable?<ErrorBox code="INVOICE_NOT_PAYABLE"/>:<><MethodCards purpose="ORDER_PAYMENT" selected={method?.code} onSelect={setMethod}/><button disabled={!method||busy} onClick={()=>void submit()}>{busy?"در حال ایجاد…":"ایجاد درخواست پرداخت سفارش"}</button></>}</div>}
