"use client";
import React from "react";
import { getTransaction, getWalletPolicy, getWalletSummary, listCredits, listReservations, listTransactions } from "../wallet/api";
import { bucketHelp, bucketLabel, creditStatusLabel, displayDate, formatRial, formatTechnicalId, formatTomanFromRial, reservationStatusLabel, transactionDirectionLabel, transactionTypeLabel, walletStatusLabel } from "../wallet/format";
import type { CreditLot, Reservation, Transaction, WalletPolicy, WalletSummary } from "../wallet/types";
type WalletPage = "overview" | "transactions" | "transaction" | "credits" | "reservations" | "policy";
type LoadState<T> = { loading: boolean; data?: T; error?: string; refreshedAt?: string };
export function WalletShell({ page, transactionReference }: { page: WalletPage; transactionReference?: string }): React.ReactElement { return <div className="wallet-page" aria-live="polite"><nav className="wallet-tabs" aria-label="ناوبری کیف پول"><a href="/wallet">نمای کلی</a><a href="/wallet/transactions">تراکنش‌ها</a><a href="/wallet/credits">اعتبارها</a><a href="/wallet/reservations">رزروها</a><a href="/wallet/policy">سیاست‌ها</a></nav>{page === "transactions" ? <Transactions /> : page === "transaction" && transactionReference ? <TransactionDetail reference={transactionReference} /> : page === "credits" ? <Credits /> : page === "reservations" ? <Reservations /> : page === "policy" ? <Policy /> : <Overview />}</div>; }
function useLoad<T>(loader: (signal: AbortSignal) => Promise<T>): [LoadState<T>, () => void] { const [tick, setTick] = React.useState(0); const [state, setState] = React.useState<LoadState<T>>({ loading: true }); React.useEffect(() => { const c = new AbortController(); setState((s) => ({ ...s, loading: true, error: undefined })); loader(c.signal).then((data) => setState({ loading: false, data, refreshedAt: new Date().toISOString() })).catch((e) => { if (!c.signal.aborted) setState((s) => ({ ...s, loading: false, error: typeof e?.code === "string" ? e.code : e instanceof Error ? e.message : "WALLET_ERROR" })); }); return () => c.abort(); }, [tick]); return [state, () => setTick((v) => v + 1)]; }
function Money({ value }: { value: number }): React.ReactElement { return <span className="money"><b>{formatRial(value)}</b><small>{formatTomanFromRial(value)}</small></span>; }
function ErrorState({ code, onRetry }: { code?: string; onRetry: () => void }): React.ReactElement { const text = code === "projection_mismatch" || code === "PROJECTION_MISMATCH" ? "اطلاعات مالی موقتاً برای نگهداری در دسترس نیست." : code === "SERVICE_UNAVAILABLE" ? "سرویس کیف پول موقتاً در دسترس نیست." : code === "AUTHENTICATION_REQUIRED" ? "برای مشاهده کیف پول ورود لازم است." : code === "CUSTOMER_BLOCKED" || code === "PERMISSION_DENIED" ? "دسترسی به این بخش طبق سیاست حساب محدود شده است." : "نمایش امن اطلاعات کیف پول ممکن نیست."; return <section className="wallet-state error"><h1>وضعیت امن کیف پول</h1><p>{text}</p><small dir="ltr">{code ?? "UNKNOWN"}</small><button onClick={onRetry}>تلاش دوباره</button></section>; }
function StatusBanner({ summary }: { summary: WalletSummary }): React.ReactElement | null { if (summary.status === "ACTIVE") return null; return <section className="wallet-state warn"><h2>{summary.status === "FROZEN" ? "کیف پول یخ‌زده است" : "کیف پول بسته است"}</h2><p>{summary.status === "FROZEN" ? "مشاهده تاریخچه مجاز است، اما خرج‌کردن و رزروهای آینده محدود خواهد بود." : "عملیات عادی کیف پول ارائه نمی‌شود و تاریخچه مجاز همچنان خواندنی است."}</p></section>; }
function Overview(): React.ReactElement { const [summary, refresh] = useLoad(getWalletSummary); const [policy] = useLoad(getWalletPolicy); const [tx] = useLoad((s) => listTransactions(undefined, s)); const [credits] = useLoad(listCredits); const [reservations] = useLoad(listReservations); if (summary.error) return <ErrorState code={summary.error} onRetry={refresh} />; if (summary.loading || !summary.data) return <Skeleton title="کیف پول" />; const expiring = credits.data?.items.find((c) => c.status === "ACTIVE" && c.expires_at); const activeReservations = reservations.data?.items.filter((r) => r.status === "ACTIVE") ?? []; return <div><header className="wallet-hero"><div><p>کیف پول مشتری</p><h1>موجودی در دسترس</h1><Money value={summary.data.available_balance_rial} /><p>موجودی در دسترس از backend می‌آید و برابر بخش قابل استفاده پس از کسر رزروهای فعال است.</p></div><span className="status-pill">● {walletStatusLabel(summary.data.status)}</span></header><StatusBanner summary={summary.data} /><section className="wallet-grid"><article><h2>رزرو شده</h2><Money value={summary.data.reserved_balance_rial} /><p>رزرو شده برای عملیات آینده نگه داشته شده و خرید تکمیل‌شده نیست.</p></article><article><h2>موجودی ثبت‌شده</h2><Money value={summary.data.posted_balance_rial} /><p>مجموع posted backend؛ مرورگر آن را محاسبه نمی‌کند.</p></article><article><h2>سیاست شارژ آینده</h2>{policy.data ? <p>از <Money value={policy.data.minimum_topup_amount_rial} /> تا <Money value={policy.data.maximum_topup_amount_rial} /></p> : <p>در حال دریافت…</p>}<p>امکان شارژ آنلاین کیف پول در مرحله پرداخت فعال خواهد شد.</p></article></section><section><h2>تفکیک سبدهای موجودی</h2><div className="wallet-grid">{summary.data.buckets.length ? summary.data.buckets.map((b) => <article key={b.bucket_type}><h3>{bucketLabel(b.bucket_type)}</h3><Money value={b.balance_rial} /><p>{bucketHelp(b.bucket_type)}</p></article>) : <p>موجودی ثبت نشده است.</p>}</div></section>{expiring ? <section className="wallet-state warn"><h2>اعتبارهای در حال انقضا</h2><p>{bucketLabel(expiring.bucket_type)} باقیمانده <Money value={expiring.remaining_amount_rial} /> تا <b>{displayDate(expiring.expires_at)}</b></p></section> : null}<section className="wallet-grid"><article><h2>تراکنش‌های اخیر</h2>{tx.data?.items.slice(0,3).map((t) => <TxCard key={t.transaction_reference} tx={t} />) ?? <p>تراکنشی برای نمایش نیست.</p>}<a href="/wallet/transactions">مشاهده همه</a></article><article><h2>رزروهای فعال</h2>{activeReservations.length ? activeReservations.map((r) => <ReservationCard key={r.reservation_reference} reservation={r} />) : <p>رزروی وجود ندارد؛ رزروها در تسویه آینده برای نگهداری موجودی استفاده می‌شوند.</p>}</article></section><button onClick={refresh}>به‌روزرسانی دستی</button>{summary.refreshedAt ? <small>آخرین دریافت: {displayDate(summary.refreshedAt)}</small> : null}</div>; }
function Transactions(): React.ReactElement { const [state, refresh] = useLoad((s) => listTransactions(undefined, s)); if (state.error) return <ErrorState code={state.error} onRetry={refresh} />; return <section><h1>تاریخچه تراکنش‌های کیف پول</h1><p>تاریخچه فقط خواندنی و cursor-paginated است؛ هیچ ویرایش یا حذف مشتری وجود ندارد.</p>{state.loading ? <Skeleton title="تراکنش‌ها" /> : state.data?.items.length ? state.data.items.map((tx) => <TxCard key={tx.transaction_reference} tx={tx} />) : <p>تراکنشی وجود ندارد.</p>}{state.data?.next_cursor ? <button onClick={refresh}>دریافت صفحه بعد</button> : null}</section>; }
function TxCard({ tx }: { tx: Transaction }): React.ReactElement { return <a className="wallet-row" href={`/wallet/transactions/${encodeURIComponent(tx.transaction_reference)}`}><b>{transactionTypeLabel(tx.type)}</b><span>{transactionDirectionLabel(tx.direction)}</span>{tx.amount_rial == null ? null : <Money value={tx.amount_rial} />}<time>{displayDate(tx.occurred_at)}</time><code dir="ltr">{formatTechnicalId(tx.transaction_reference)}</code></a>; }
function TransactionDetail({ reference }: { reference: string }): React.ReactElement { const [state, refresh] = useLoad((s) => getTransaction(reference, s)); if (state.error) return <ErrorState code={state.error} onRetry={refresh} />; if (state.loading || !state.data) return <Skeleton title="جزئیات تراکنش" />; const tx = state.data; return <section><h1>جزئیات تراکنش</h1><Field label="شناسه امن" value={<code dir="ltr">{formatTechnicalId(tx.transaction_reference)}</code>} /><Field label="نوع" value={transactionTypeLabel(tx.type)} /><Field label="جهت" value={transactionDirectionLabel(tx.direction)} />{tx.amount_rial != null ? <Field label="مبلغ" value={<Money value={tx.amount_rial} />} /> : null}<Field label="زمان رخداد" value={displayDate(tx.occurred_at)} /><Field label="وضعیت" value={tx.status} />{tx.reversal_of_reference ? <Field label="برگشت مرتبط" value={<code dir="ltr">{formatTechnicalId(tx.reversal_of_reference)}</code>} /> : null}<button onClick={() => void navigator.clipboard?.writeText(tx.transaction_reference)}>کپی شناسه امن</button></section>; }
function Credits(): React.ReactElement { const [state, refresh] = useLoad(listCredits); if (state.error) return <ErrorState code={state.error} onRetry={refresh} />; return <section><h1>اعتبارها و انقضا</h1>{state.loading ? <Skeleton title="اعتبارها" /> : state.data?.items.length ? state.data.items.map((c) => <CreditCard key={c.credit_reference} credit={c} />) : <p>اعتبار تاریخ‌دار وجود ندارد.</p>}</section>; }
function CreditCard({ credit }: { credit: CreditLot }): React.ReactElement { return <article className="wallet-row"><b>{bucketLabel(credit.bucket_type)}</b><Money value={credit.remaining_amount_rial} /><span>{creditStatusLabel(credit.status)}</span><span>صدور: {displayDate(credit.issued_at ?? null)}</span><span>انقضا: {displayDate(credit.expires_at)}</span><code dir="ltr">{formatTechnicalId(credit.credit_reference)}</code></article>; }
function Reservations(): React.ReactElement { const [state, refresh] = useLoad(listReservations); if (state.error) return <ErrorState code={state.error} onRetry={refresh} />; return <section><h1>رزروهای کیف پول</h1><p>رزروها خرید تکمیل‌شده یا سفارش نیستند و این رابط امکان ایجاد، برداشت یا آزادسازی رزرو ندارد.</p>{state.loading ? <Skeleton title="رزروها" /> : state.data?.items.length ? state.data.items.map((r) => <ReservationCard key={r.reservation_reference} reservation={r} />) : <p>رزروی وجود ندارد؛ در تسویه آینده برای نگهداری موقت موجودی استفاده خواهد شد.</p>}</section>; }
function ReservationCard({ reservation }: { reservation: Reservation }): React.ReactElement { return <article className="wallet-row"><b>{reservationStatusLabel(reservation.status)}</b><Money value={reservation.amount_rial} /><span>{reservation.purpose_code ?? "هدف عمومی آینده"}</span><span>انقضا: {displayDate(reservation.expires_at)}</span><code dir="ltr">{formatTechnicalId(reservation.reservation_reference)}</code></article>; }
function Policy(): React.ReactElement { const [state, refresh] = useLoad(getWalletPolicy); if (state.error) return <ErrorState code={state.error} onRetry={refresh} />; if (state.loading || !state.data) return <Skeleton title="سیاست کیف پول" />; const p: WalletPolicy = state.data; return <section><h1>سیاست‌ها و محدودیت‌های کیف پول</h1><Field label="واحد پول" value="IRR / ریال" /><Field label="حداقل شارژ آینده" value={<Money value={p.minimum_topup_amount_rial} />} /><Field label="حداکثر شارژ آینده" value={<Money value={p.maximum_topup_amount_rial} />} />{p.maximum_wallet_balance_rial ? <Field label="حداکثر موجودی" value={<Money value={p.maximum_wallet_balance_rial} />} /> : null}<Field label="عملیات مشتری" value={p.customer_wallet_operations_enabled ? "فعال طبق backend" : "غیرفعال طبق backend"} /><p className="wallet-state warn">امکان شارژ آنلاین کیف پول در مرحله پرداخت فعال خواهد شد. هیچ دکمه پرداخت، فرم مبلغ یا مسیر تسویه فعال در این milestone وجود ندارد.</p></section>; }
function Field({ label, value }: { label: string; value: React.ReactNode }): React.ReactElement { return <div className="field"><span>{label}</span><b>{value}</b></div>; }
function Skeleton({ title }: { title: string }): React.ReactElement { return <section className="wallet-state"><h1>{title}</h1><p>در حال دریافت امن اطلاعات از backend…</p></section>; }
