import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const root = new URL("../", import.meta.url);
function source(path) { return readFileSync(new URL(path, root), "utf8"); }
assert.match(source("telegram/adapter.ts"), /initData\?/) ;
assert.doesNotMatch(source("telegram/adapter.ts"), /initDataUnsafe/);
assert.doesNotMatch(source("auth/token-store.ts"), /localStorage|sessionStorage|indexedDB|cookie/i);
assert.match(source("auth/api-client.ts"), /credentials: "include"/);
assert.match(source("auth/api-client.ts"), /authorization/);
assert.match(source("auth/api-client.ts"), /refreshInFlight \?\?=/);
assert.match(source("auth/api-client.ts"), /retry && path !== "\/refresh"/);
assert.match(source("auth/bootstrap.ts"), /bootstrapPromise/);
assert.match(source("auth/state-machine.ts"), /INITIALIZING/);
assert.match(source("auth/state-machine.ts"), /RATE_LIMITED/);
assert.match(source("components/CustomerApp.tsx"), /dir=\{ltr \? "ltr"/);
assert.match(source("components/CustomerApp.tsx"), /--safe-bottom/);
assert.match(source("components/CustomerApp.tsx"), /fa\.states\.browser/);
assert.match(source("components/CustomerApp.tsx"), /کیف پول/);
assert.match(source("catalog/api.ts"), /\/api\/v1\/catalog/);
assert.match(source("catalog/api.ts"), /quotes\/preview/);
assert.match(source("catalog/api.ts"), /Idempotency-Key/);
assert.match(source("catalog/format.ts"), /formatTomanFromRial/);
assert.match(source("catalog/format.ts"), /Number\.isSafeInteger/);
assert.match(source("catalog/builder.ts"), /validateSelection/);
assert.match(source("catalog/preview-controller.ts"), /AbortController/);
assert.match(source("catalog/comparison.ts"), /COMPARISON_LIMIT = 3/);
assert.match(source("components/Catalog.tsx"), /fa\.catalog\.nonBinding/);
assert.match(source("components/Catalog.tsx"), /validateComponentSum/);
assert.doesNotMatch(source("components/Catalog.tsx"), /server ip|inbound|provider|panel/i);
assert.doesNotMatch(source("catalog/api.ts"), /localStorage|sessionStorage|indexedDB|initDataUnsafe/i);

assert.match(source("wallet/api.ts"), /\/api\/v1\/customer\/wallet/);
assert.match(source("wallet/api.ts"), /Number\.isSafeInteger|assertSafeRial/);
assert.match(source("wallet/api.ts"), /available \+ reserved !== posted/);
assert.doesNotMatch(source("wallet/api.ts"), /localStorage|sessionStorage|indexedDB|initDataUnsafe/i);
assert.match(source("wallet/format.ts"), /formatRial/);
assert.match(source("wallet/format.ts"), /formatTomanFromRial/);
assert.match(source("wallet/format.ts"), /PROMOTIONAL/);
assert.match(source("components/Wallet.tsx"), /موجودی در دسترس/);
assert.match(source("components/Wallet.tsx"), /امکان شارژ آنلاین کیف پول در مرحله پرداخت فعال خواهد شد/);
assert.doesNotMatch(source("components/Wallet.tsx"), /checkout|payment|invoice|provider|server ip|inbound/i);
assert.match(source("wallet/format.ts"), /Number\.isSafeInteger/);
assert.match(source("wallet/format.ts"), /const toman = Math\.trunc\(value \/ 10\)/);
assert.match(source("wallet/format.ts"), /value % 10/);

assert.match(source("commerce/api.ts"), /\/api\/v1\/customer/);
assert.match(source("commerce/api.ts"), /payment_method:\"WALLET\"/);
assert.doesNotMatch(source("commerce/api.ts"), /price_components|wallet_balance|customer_identity/);
assert.match(source("commerce/api.ts"), /invoice_amount_mismatch/);
assert.match(source("commerce/idempotency.ts"), /getRandomValues/);
assert.doesNotMatch(source("commerce/idempotency.ts"), /localStorage|sessionStorage|indexedDB/i);
assert.match(source("components/Commerce.tsx"), /READY_FOR_FULFILLMENT/);
assert.match(source("components/Commerce.tsx"), /هیچ سرویس\/QR\/لینکی اکنون تحویل داده نمی‌شود/);
assert.match(source("components/Commerce.tsx"), /role=\"dialog\"/);
assert.match(source("components/Commerce.tsx"), /پرداخت فعلاً فقط از کیف پول/);
assert.doesNotMatch(source("components/Commerce.tsx"), /card-number|crypto|gateway|server ip|inbound|subscription URL/i);
assert.doesNotMatch(source("commerce/api.ts"), /localStorage|sessionStorage|indexedDB|initDataUnsafe/i);
