import { correlationId } from "../auth/api-client"; import { getAccessToken } from "../auth/token-store"; import { loadCustomerConfig } from "../config/public-config"; import { assertSafeRial } from "./format"; import type { CheckoutResult, CommerceError, Invoice, Order, Page, TimelineEvent } from "./types";
type Fetcher=typeof fetch; const config=loadCustomerConfig(); function headers(extra?:Record<string,string>):Headers{const h=new Headers(extra); h.set("content-type","application/json"); h.set("x-request-id",correlationId()); const t=getAccessToken(); if(t) h.set("authorization",`Bearer ${t}`); return h;}
async function err(r:Response):Promise<CommerceError>{let code=r.status===401?"AUTHENTICATION_REQUIRED":r.status>=500?"SERVICE_UNAVAILABLE":"COMMERCE_ERROR";let cid; const d=await r.json().catch(()=>null) as {detail?:{code?:string;correlation_id?:string}}|null; if(d?.detail?.code) code=d.detail.code; cid=d?.detail?.correlation_id; return {code,message:code,correlationId:cid,retryAfter:r.headers.get("retry-after")};}
function obj(v:unknown):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v)) throw new Error("invalid_response"); return v as Record<string,unknown>;} function str(v:unknown,f:string):string{if(typeof v!=="string") throw new Error(`invalid_${f}`); return v;} function date(v:unknown,f:string):string{const s=str(v,f); if(Number.isNaN(Date.parse(s))) throw new Error(`invalid_${f}`); return s;} function optDate(v:unknown,f:string):string|null{return v==null?null:date(v,f);}
export function validateOrder(v:unknown):Order{const o=obj(v); if(o.currency!=="IRR") throw new Error("invalid_currency"); return {order_reference:str(o.order_reference,"order_reference"),checkout_reference:typeof o.checkout_reference==="string"?o.checkout_reference:null,invoice_reference:typeof o.invoice_reference==="string"?o.invoice_reference:null,status:str(o.status,"status"),financial_status:str(o.financial_status,"financial_status"),fulfillment_status:str(o.fulfillment_status,"fulfillment_status"),final_amount_rial:assertSafeRial(o.final_amount_rial,"final_amount_rial"),currency:"IRR",created_at:date(o.created_at,"created_at"),paid_at:optDate(o.paid_at,"paid_at"),cancelled_at:optDate(o.cancelled_at,"cancelled_at"),snapshot:obj(o.snapshot)};}
export function validateInvoice(v:unknown):Invoice{const o=obj(v); if(o.currency!=="IRR") throw new Error("invalid_currency"); const lines=Array.isArray(o.lines)?o.lines.map((x)=>{const l=obj(x); return {line_type:str(l.line_type,"line_type"),description:str(l.description,"description"),quantity:assertSafeRial(l.quantity,"quantity"),unit_amount_rial:assertSafeRial(l.unit_amount_rial,"unit_amount_rial"),line_subtotal_rial:assertSafeRial(l.line_subtotal_rial,"line_subtotal_rial"),position:assertSafeRial(l.position,"position")};}):[]; const subtotal=assertSafeRial(o.subtotal_rial,"subtotal_rial"); const lineSum=lines.reduce((a,l)=>a+l.line_subtotal_rial,0); if(lines.length&&lineSum!==subtotal) throw new Error("invoice_amount_mismatch"); const payable=assertSafeRial(o.payable_total_rial,"payable_total_rial"); const adj=assertSafeRial(o.adjustment_total_rial,"adjustment_total_rial"); const disc=assertSafeRial(o.discount_total_rial,"discount_total_rial"); const tax=assertSafeRial(o.tax_total_rial,"tax_total_rial"); if(subtotal+adj-disc+tax!==payable) throw new Error("invoice_amount_mismatch"); return {invoice_reference:str(o.invoice_reference,"invoice_reference"),order_reference:str(o.order_reference,"order_reference"),status:str(o.status,"status"),currency:"IRR",subtotal_rial:subtotal,adjustment_total_rial:adj,discount_total_rial:disc,tax_total_rial:tax,payable_total_rial:payable,paid_total_rial:assertSafeRial(o.paid_total_rial,"paid_total_rial"),issued_at:date(o.issued_at,"issued_at"),due_at:date(o.due_at,"due_at"),paid_at:optDate(o.paid_at,"paid_at"),cancelled_at:optDate(o.cancelled_at,"cancelled_at"),lines};}
function validateCheckout(v:unknown):CheckoutResult{const o=obj(v), c=obj(o.checkout); return {checkout:{checkout_reference:str(c.checkout_reference,"checkout_reference"),status:str(c.status,"status"),reservation_amount_rial:c.reservation_amount_rial==null?undefined:assertSafeRial(c.reservation_amount_rial,"reservation_amount_rial"),expires_at:typeof c.expires_at==="string"?date(c.expires_at,"expires_at"):undefined},order:validateOrder(o.order),invoice:validateInvoice(o.invoice)};}
async function json<T>(path:string, validate:(v:unknown)=>T, init:RequestInit={}, fetcher:Fetcher=fetch):Promise<T>{const r=await fetcher(`${config.apiBaseUrl}/api/v1/customer${path}`,{...init,headers:headers(init.headers as Record<string,string>|undefined),credentials:"include",cache:"no-store"}); if(!r.ok) throw await err(r); return validate(await r.json());}
export const createCheckout=(quoteReference:string,key:string,signal?:AbortSignal)=>json("/checkout",validateCheckout,{method:"POST",signal,headers:{"Idempotency-Key":key},body:JSON.stringify({quote_reference:quoteReference,payment_method:"WALLET"})});
export const confirmCheckout=(ref:string,signal?:AbortSignal)=>json(`/checkout/${encodeURIComponent(ref)}/confirm`,validateCheckout,{method:"POST",signal,body:JSON.stringify({})});
export const cancelCheckout=(ref:string,reason:string,signal?:AbortSignal)=>json(`/checkout/${encodeURIComponent(ref)}/cancel`,(v)=>({order:validateOrder(obj(v).order)}),{method:"POST",signal,body:JSON.stringify({reason_code:"CUSTOMER_REQUEST",reason})});
function page<T>(v:unknown, item:(x:unknown)=>T):Page<T>{const o=obj(v);return {items:Array.isArray(o.items)?o.items.map(item):[],next_cursor:typeof o.next_cursor==="string"?o.next_cursor:null};}
export const listOrders=(signal?:AbortSignal)=>json("/orders",(v)=>page(v,validateOrder),{signal}); export const getOrder=(r:string,signal?:AbortSignal)=>json(`/orders/${encodeURIComponent(r)}`,validateOrder,{signal}); export const getTimeline=(r:string,signal?:AbortSignal)=>json(`/orders/${encodeURIComponent(r)}/timeline`,(v)=>page(v,(x)=>{const o=obj(x);return {event_code:str(o.event_code,"event_code"),occurred_at:date(o.occurred_at,"occurred_at"),actor_type:typeof o.actor_type==="string"?o.actor_type:undefined,metadata:obj(o.metadata??{})} as TimelineEvent;}),{signal}); export const listInvoices=(signal?:AbortSignal)=>json("/invoices",(v)=>page(v,validateInvoice),{signal}); export const getInvoice=(r:string,signal?:AbortSignal)=>json(`/invoices/${encodeURIComponent(r)}`,validateInvoice,{signal});
