"use client";
import React from "react";
import { cx } from "../internal/cx";
export const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(function Input({className,...p},ref){return <input ref={ref} className={cx("ui-input",className)} {...p}/>});
export const PasswordInput=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function PasswordInput(p,ref){return <Input {...p} ref={ref} type="password"/>});
export const SearchInput=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function SearchInput(p,ref){return <Input {...p} ref={ref} type="search"/>});
export const Textarea=React.forwardRef<HTMLTextAreaElement,React.TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({className,...p},ref){return <textarea ref={ref} className={cx("ui-input",className)} {...p}/>});
export const Select=React.forwardRef<HTMLSelectElement,React.SelectHTMLAttributes<HTMLSelectElement>>(function Select({className,...p},ref){return <select ref={ref} className={cx("ui-input",className)} {...p}/>});
export function Field({label,hint,error,children}:{label:React.ReactNode;hint?:React.ReactNode;error?:React.ReactNode;children:React.ReactElement<React.HTMLAttributes<HTMLElement>&{id?:string}>}){const base=React.useId();const controlId=children.props.id??`${base}-control`;const hintId=hint?`${base}-hint`:undefined;const errorId=error?`${base}-error`:undefined;const supplied=children.props["aria-describedby"] as string|undefined;const described=[supplied,hintId,errorId].filter(Boolean).join(" ")||undefined;return <div className="ui-field"><label htmlFor={controlId}>{label}</label>{React.cloneElement(children,{id:controlId,"aria-describedby":described,"aria-invalid":error?true:children.props["aria-invalid"]})}{hint&&<small id={hintId} className="ui-muted">{hint}</small>}{error&&<small id={errorId} className="ui-danger" role="alert">{error}</small>}</div>}
export const Checkbox=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function Checkbox(p,ref){return <input {...p} ref={ref} type="checkbox" className={cx("ui-check",p.className)}/>});
export const Radio=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(function Radio(p,ref){return <input {...p} ref={ref} type="radio" className={cx("ui-check",p.className)}/>});
export const Switch=React.forwardRef<HTMLInputElement,Omit<React.InputHTMLAttributes<HTMLInputElement>,"type">>(function Switch(p,ref){return <input {...p} ref={ref} type="checkbox" role="switch" className={cx("ui-switch",p.className)}/>});
export function FormMessage({tone="neutral",children}:{tone?:string;children:React.ReactNode}){return <p className={cx("ui-form-message",`ui-${tone}`)} role={tone==="danger"?"alert":"status"}>{children}</p>}
