"use client";
import React from "react";
import { Button } from "../actions";
import { cx } from "../internal/cx";
export type ModalProps={open:boolean;title:string;onClose:()=>void;children:React.ReactNode;closeLabel?:string;className?:string};
export function Modal({open,title,onClose,children,closeLabel="Close",className}:ModalProps){const dialog=React.useRef<HTMLDialogElement>(null);const titleId=React.useId();const trigger=React.useRef<HTMLElement|null>(null);React.useEffect(()=>{const node=dialog.current;if(!node)return;if(open&&!node.open){trigger.current=document.activeElement as HTMLElement;node.showModal();queueMicrotask(()=>node.querySelector<HTMLElement>("button,[href],input,select,textarea,[tabindex]:not([tabindex='-1'])")?.focus())}else if(!open&&node.open)node.close();},[open]);const close=()=>{onClose();queueMicrotask(()=>trigger.current?.focus())};return <dialog ref={dialog} className={cx("ui-dialog",className)} aria-labelledby={titleId} onCancel={e=>{e.preventDefault();close()}} onClose={()=>{if(open)onClose();trigger.current?.focus()}}><h2 id={titleId}>{title}</h2>{children}<Button variant="ghost" className="ui-dialog-close" aria-label={closeLabel} onClick={close}>×</Button></dialog>}
export function ConfirmDialog({open,title,description,confirmLabel,cancelLabel,onConfirm,onCancel,onClose}:{open:boolean;title:string;description:string;confirmLabel:string;cancelLabel:string;onConfirm:()=>void;onCancel?:()=>void;onClose?:()=>void}){const cancel=()=>{onCancel?.();onClose?.()};return <Modal open={open} title={title} onClose={cancel}><p>{description}</p><div className="ui-actions"><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button><Button variant="secondary" onClick={cancel}>{cancelLabel}</Button></div></Modal>}
export function Drawer({placement="end",...props}:ModalProps&{placement?:"start"|"end"}){return <Modal {...props} className={cx("ui-drawer",`ui-drawer--${placement}`,props.className)}/>}
export function BottomSheet(props:ModalProps){return <Modal {...props} className={cx("ui-bottom-sheet",props.className)}/>}
export function DropdownMenu({label,children}:{label:string;children:React.ReactNode}){const ref=React.useRef<HTMLDetailsElement>(null);return <details ref={ref} className="ui-menu" onKeyDown={e=>{if(e.key==="Escape"){ref.current?.removeAttribute("open");(ref.current?.querySelector("summary") as HTMLElement)?.focus()}}}><summary>{label}</summary><div>{children}</div></details>}
export function Tooltip({label,children}:{label:string;children:React.ReactElement<React.HTMLAttributes<HTMLElement>>}){const id=React.useId();const[visible,setVisible]=React.useState(false);return <span className="ui-tooltip" onFocus={()=>setVisible(true)} onBlur={()=>setVisible(false)} onMouseEnter={()=>setVisible(true)} onMouseLeave={()=>setVisible(false)} onKeyDown={e=>{if(e.key==="Escape")setVisible(false)}}>{React.cloneElement(children,{"aria-describedby":visible?id:undefined})}{visible&&<span role="tooltip" id={id}>{label}</span>}</span>}
