import { catalogFa } from "../i18n/catalog";
import { catalogPermissions } from "../catalog/policy";
type Props = { title: string; required?: string; children?: React.ReactNode; state?: "ok"|"forbidden"|"unavailable"|"error" };
const nav = [ ["/catalog", catalogFa.overview, "catalog.read"], ["/catalog/categories", catalogFa.categories, "catalog.read"], ["/catalog/products", catalogFa.products, "catalog.read"], ["/catalog/price-lists", catalogFa.priceLists, "pricing.read"], ["/catalog/states/validation-errors", "خطاهای انتشار", "catalog.publish"] ];
export function CatalogShell({ title, required = "catalog.read", children, state = "ok" }: Props): React.ReactElement { return <main className="mgmt-shell catalog-shell" dir="rtl"><aside className="mgmt-side"><div className="brand">VPN-SALE</div><p>کنسول کاتالوگ Milestone 2-B1</p><nav aria-label="ناوبری کاتالوگ" className="mgmt-nav">{nav.map(([href,label,perm])=><a key={href} href={href} data-permission={perm}>{label}</a>)}</nav><small>مجوزهای کاتالوگ: {catalogPermissions.join("، ")}. مخفی‌سازی کنترل‌ها امنیت نیست؛ بک‌اند مرجع نهایی است.</small></aside><section className="mgmt-main"><header className="mgmt-top"><div><p className="eyebrow">مجوز: <code className="tech">{required}</code></p><h1>{title}</h1></div><a className="pill" href="/security/profile">بازخوانی پروفایل</a></header>{state !== "ok" ? <CatalogState state={state}/> : children}</section></main>; }
export function CatalogState({ state }: { state: "forbidden"|"unavailable"|"error" }): React.ReactElement { const copy = state === "forbidden" ? [catalogFa.unauthorized,"درخواست مستقیم به مسیر بدون مجوز با حالت کنترل‌شده ۴۰۳ نمایش داده می‌شود."] : state === "unavailable" ? [catalogFa.unavailable,"درخواست‌ها قابل تکرارند و بدنه پاسخ یا توکن‌ها لاگ نمی‌شوند."] : [catalogFa.error,"خطای ناشناخته با پیام محلی امن و شناسه همبستگی نمایش داده می‌شود."]; return <section className="panel safe-state" role="alert"><h2>{copy[0]}</h2><p>{copy[1]}</p><a className="btn secondary" href="/catalog">بازگشت به کاتالوگ</a></section>; }
export function Field({ label, children, hint }: { label: string; children?: React.ReactNode; hint?: string }): React.ReactElement { return <label className="field"><span>{label}</span>{children}{hint ? <small className="muted">{hint}</small> : null}</label>; }
export function ErrorSummary({ errors = [] }: { errors?: string[] }): React.ReactElement | null { return errors.length ? <div className="notice error" role="alert" tabIndex={-1}><strong>خطاهای فرم</strong><ul>{errors.map((e)=><li key={e}>{e}</li>)}</ul></div> : null; }
export function DataActions({ children }: { children: React.ReactNode }): React.ReactElement { return <div className="actions">{children}</div>; }
