import { StatusBadge, Tech } from './ManagementShell';
import { financeNav } from '../finance/permissions';
import { formatRial, formatToman } from '../finance/money';
import type { Balance, Posting } from '../finance/types';
import { directionLabel } from '../finance/format';

type Props = { title: string; required?: string; children?: React.ReactNode; state?: 'normal'|'forbidden'|'unavailable'|'error' };
export function FinanceShell({ title, required, children, state='normal' }: Props): React.ReactElement { return <main className="mgmt-shell finance-shell"><aside className="mgmt-side"><div className="brand">VPN-SALE</div><p>کنسول مالی مدیریتی</p><nav aria-label="ناوبری مالی" className="mgmt-nav">{financeNav.map((item)=><a key={item.href} href={item.href}>{item.label}</a>)}</nav><small>داده‌های مالی در storage مرورگر ذخیره نمی‌شود؛ بک‌اند مرجع مجوز و موجودی است.</small></aside><section className="mgmt-main"><header className="mgmt-top"><div><p className="eyebrow">{required ? `مجوز: ${required}` : 'Milestone 3-A2B'}</p><h1>{title}</h1></div><a className="pill" href="/management/security-events">مرکز امنیت</a></header>{state!=='normal' ? <FinancialState state={state}/> : children}</section></main>; }
export function Money({ value }: { value: number }): React.ReactElement { return <span className="money"><b>{formatRial(value)}</b><small>{formatToman(value)}</small></span>; }
export function BalanceCards({ balance }: { balance: Balance }): React.ReactElement { return <section className="cards" aria-label="تفکیک موجودی"><article className="panel metric primary"><span>موجودی قابل استفاده</span><strong><Money value={balance.available_balance_rial}/></strong><small>قابل خرج از نگاه مشتری؛ مقدار سرور.</small></article><article className="panel metric"><span>موجودی ثبت‌شده</span><strong><Money value={balance.posted_balance_rial}/></strong><small>مانده دفترکل، لزوماً آزاد نیست.</small></article><article className="panel metric"><span>موجودی رزروشده</span><strong><Money value={balance.reserved_balance_rial}/></strong><small>نگه‌داری موقت، خرج‌شده نامیده نمی‌شود.</small></article></section>; }
export function PostingTable({ postings=[] }: { postings?: Posting[] }): React.ReactElement { const debit=postings.filter(p=>p.direction==='DEBIT').reduce((s,p)=>s+p.amount_rial,0); const credit=postings.filter(p=>p.direction==='CREDIT').reduce((s,p)=>s+p.amount_rial,0); return <section className="panel"><h2>پستینگ‌های تغییرناپذیر</h2><p className="notice">در این پلتفرم Credit به حساب بدهی کیف‌پول، موجودی مشتری را افزایش می‌دهد و Debit آن را کاهش می‌دهد. اعداد همیشه مثبت و ریال هستند.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>ردیف</th><th>حساب</th><th>جهت</th><th>Debit</th><th>Credit</th><th>هدف</th></tr></thead><tbody>{postings.map((p,i)=><tr key={`${p.account_code}-${i}`}><td data-label="ردیف">{p.posting_order??i+1}</td><td data-label="حساب"><Tech>{p.account_code}</Tech></td><td data-label="جهت">{directionLabel(p.direction)}</td><td data-label="Debit">{p.direction==='DEBIT'?<Money value={p.amount_rial}/>: '—'}</td><td data-label="Credit">{p.direction==='CREDIT'?<Money value={p.amount_rial}/>: '—'}</td><td data-label="هدف"><Tech>{p.purpose_code}</Tech></td></tr>)}</tbody></table></div><p className={debit===credit?'ok':'error'}>جمع بدهکار: {formatRial(debit)} / جمع بستانکار: {formatRial(credit)} — {debit===credit?'تراز است':'هشدار بحرانی: سند تراز نیست'}</p></section>; }
export function FinancialState({ state }: { state: 'forbidden'|'unavailable'|'error'|'notfound' }): React.ReactElement { const text={forbidden:'دسترسی مالی مجاز نیست. تغییر مجوز پس از refresh امن پروفایل اعمال می‌شود.',unavailable:'سرویس مالی موقتاً در دسترس نیست. Retry-After و correlation ID در خطای ساختاری نمایش داده می‌شود.',error:'خطای مالی امن رخ داد؛ پاسخ خام، stack trace و داده حساس نمایش داده نمی‌شود.',notfound:'رکورد مالی پیدا نشد.'}[state]; return <section className="empty safe-state"><h2>{text}</h2><StatusBadge value={state}/></section>; }
export function ActionLinks({ walletId='[walletId]' }: { walletId?: string }): React.ReactElement { return <div className="actions"><a className="btn" href={`/management/wallets/${walletId}/adjustments/credit`}>اعتبار دستی</a><a className="btn secondary" href={`/management/wallets/${walletId}/adjustments/debit`}>بدهی دستی</a><a className="btn secondary" href={`/management/wallets/${walletId}/transactions`}>تاریخچه</a><a className="btn danger" href={`/management/wallets/${walletId}/freeze`}>مسدودسازی</a><a className="btn secondary" href="/management/ledger">دفترکل</a></div>; }
