"use client";
import React from "react";
import { getProfile } from "../auth/api-client";
import { effectivePermissions } from "../management/permissions";
import { fa } from "../i18n/management";
import { managementNav } from "../management/permissions";
type Props = { title: string; eyebrow?: string; children?: React.ReactNode; required?: string };
export function ManagementShell({ title, eyebrow = "مدیریت هویت و امنیت", children, required }: Props): React.ReactElement { const [manual,setManual]=React.useState(false); React.useEffect(()=>{void getProfile().then(p=>setManual(effectivePermissions(p).has("manual_topups.read"))).catch(()=>setManual(false))},[]); return <main className="mgmt-shell"><aside className="mgmt-side"><div className="brand">VPN-SALE</div><p>{eyebrow}</p><nav aria-label="ناوبری مدیریت" className="mgmt-nav">{managementNav.map((item)=><a key={item.href} href={item.href}>{item.label}</a>)}<a href="/management/operations/readiness">آمادگی عملیاتی</a><a href="/management/quality">کیفیت و انتشار</a><a href="/management/releases/candidates">Release Candidates</a><a href="/management/releases/go-no-go">Go/No-Go</a><a href="/management/commerce">عملیات تجارت</a><a href="/management/payments">عملیات پرداخت</a><a href="/management/payment-methods">روش‌های پرداخت</a>{manual ? <a href="/management/manual-topups">واریزهای کارت‌به‌کارت</a> : null}<a href="/management/payment-intents">نیت‌های پرداخت</a><a href="/management/payment-webhooks">صندوق وبهوک</a></nav><small>نمایش واقعی مجوزها پس از refresh امن پروفایل اعمال می‌شود؛ بک‌اند مرجع نهایی است.</small></aside><section className="mgmt-main"><header className="mgmt-top"><div><p className="eyebrow">{required ? `مجوز: ${required}` : "Milestone 1D-B"}</p><h1>{title}</h1></div><a className="pill" href="/security/profile">{fa.nav.personal}</a></header>{children}</section></main>; }
export function StatusBadge({ value }: { value?: string | boolean | null }): React.ReactElement { return <span className="status"><span aria-hidden="true">●</span>{String(value ?? "—")}</span>; }
export function Tech({ children }: { children?: React.ReactNode }): React.ReactElement { return <code className="tech" dir="ltr">{children ?? "—"}</code>; }
export function EmptyState({ title, body }: { title: string; body: string }): React.ReactElement { return <section className="empty"><h2>{title}</h2><p>{body}</p></section>; }
export function ConfirmBox({ label = "علت عملیات", action = "تأیید عملیات حساس" }: { label?: string; action?: string }): React.ReactElement { return <form className="confirm" aria-label="تأیید عملیات"><label>{label}<textarea maxLength={240} required /></label><button className="btn danger" type="button">{action}</button></form>; }
