import type { TelegramAdapter } from "../telegram/adapter";
import { browserBootstrap, getAuthCapabilities, telegramLogin, getProfile, getSessions } from "./api-client";
import { CustomerApiError } from "./error-map";
import type { AuthCapabilities, CustomerAuthState, CustomerProfile, CustomerSession } from "./types";
let bootstrapPromise: Promise<BootstrapResult> | null = null;
export type BootstrapResult = { state: CustomerAuthState; profile?: CustomerProfile; sessions?: CustomerSession[]; capabilities?: AuthCapabilities; error?: string };
export async function bootstrapCustomer(adapter: TelegramAdapter, fetcher: typeof fetch = fetch): Promise<BootstrapResult> { if (bootstrapPromise) return bootstrapPromise; bootstrapPromise = run(adapter, fetcher).finally(() => { bootstrapPromise = null; }); return bootstrapPromise; }
async function run(adapter: TelegramAdapter, fetcher: typeof fetch): Promise<BootstrapResult> { const capabilities = await getAuthCapabilities(fetcher); try { await browserBootstrap(fetcher); const [profile, sessions] = await Promise.all([getProfile(fetcher), getSessions(fetcher)]); return { state: "AUTHENTICATED", profile, sessions, capabilities }; } catch (error) { if (!(error instanceof CustomerApiError) || error.status !== 401) throw error; } if (!adapter.isAvailable()) return { state: "TELEGRAM_UNAVAILABLE", capabilities }; if (!adapter.isSupported()) return { state: "UNSUPPORTED_CLIENT", capabilities }; adapter.expand(); const initData = adapter.getInitData(); if (!initData.trim()) { adapter.ready(); return { state: "UNAUTHORIZED", capabilities, error: "empty_init_data" }; } await telegramLogin(initData, fetcher); const [profile, sessions] = await Promise.all([getProfile(fetcher), getSessions(fetcher)]); adapter.ready(); return { state: "AUTHENTICATED", profile, sessions, capabilities }; }
export function resetBootstrapForTests(): void { bootstrapPromise = null; }
