import {getAccessToken,getCsrfToken} from '../auth/token-store';import {loadCustomerConfig} from '../config/public-config';import type{ManualTopup,ManualTopupPage}from'./types';import{safeError}from'./format';
const base=()=>`${loadCustomerConfig().apiBaseUrl}/api/v1/customer/manual-topups`;export const logicalKey=():string=>crypto.randomUUID();
function headers(key?:string):Headers{const h=new Headers();const token=getAccessToken(),csrf=getCsrfToken();if(token)h.set('authorization',`Bearer ${token}`);if(csrf)h.set('x-csrf-token',csrf);if(key)h.set('Idempotency-Key',key);return h}
async function call<T>(path:string,init:RequestInit={},key?:string):Promise<T>{const h=headers(key);if(!(init.body instanceof FormData))h.set('content-type','application/json');const r=await fetch(`${base()}${path}`,{...init,headers:h,credentials:'include',cache:'no-store'});if(!r.ok)throw new Error(safeError(r.status));return r.json()as Promise<T>}
export const createManualTopup=(amountRial:number,key:string,signal?:AbortSignal)=>call<ManualTopup>('',{method:'POST',body:JSON.stringify({amount_rial:amountRial,source_channel:'WEB'}),signal},key);
export const listManualTopups=(signal?:AbortSignal)=>call<ManualTopupPage>('',{signal});export const getManualTopup=(reference:string,signal?:AbortSignal)=>call<ManualTopup>(`/${encodeURIComponent(reference)}`,{signal});
export const cancelManualTopup=(reference:string,key:string)=>call<ManualTopup>(`/${encodeURIComponent(reference)}/cancel`,{method:'POST',body:'{}'},key);
export function uploadReceipt(reference:string,file:File,key:string,onProgress:(value:number)=>void,signal:AbortSignal):Promise<ManualTopup>{return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest(),form=new FormData();form.set('image',file);xhr.open('POST',`${base()}/${encodeURIComponent(reference)}/receipts`);headers(key).forEach((v,k)=>xhr.setRequestHeader(k,v));xhr.withCredentials=true;xhr.upload.onprogress=e=>e.lengthComputable&&onProgress(Math.round(e.loaded/e.total*100));xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)resolve(JSON.parse(xhr.responseText)as ManualTopup);else reject(new Error(safeError(xhr.status)))};xhr.onerror=()=>reject(new Error('بارگذاری انجام نشد. دوباره تلاش کنید.'));const abort=()=>xhr.abort();signal.addEventListener('abort',abort,{once:true});xhr.onloadend=()=>signal.removeEventListener('abort',abort);xhr.send(form)})}
export async function privateReceiptObjectUrl(reference:string,signal:AbortSignal):Promise<string>{const r=await fetch(`${base()}/${encodeURIComponent(reference)}/receipt`,{headers:headers(),credentials:'include',cache:'no-store',signal});if(!r.ok||!r.headers.get('content-type')?.startsWith('image/'))throw new Error('نمایش فیش ممکن نیست.');return URL.createObjectURL(await r.blob())}
