import { refreshOnce } from "../auth/api-client";
import { getAccessToken, getCsrfToken } from "../auth/token-store";
import type { AdminRecord, AuditEvent, Customer, ManagementError, ManagementSession, Page, Permission, RoleSummary, SecurityEvent } from "./types";

declare const process: { env: { NEXT_PUBLIC_API_BASE_URL?: string } };
const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";
type Query = Record<string, string | number | boolean | null | undefined>;
export class ManagementApiError extends Error { detail: ManagementError; constructor(detail: ManagementError){ super(detail.code); this.detail = detail; } }
export function serializeQuery(query: Query = {}): string { const p = new URLSearchParams(); for (const [k,v] of Object.entries(query)){ if(v !== undefined && v !== null && String(v) !== "") p.set(k, String(v).slice(0, 240)); } const s = p.toString(); return s ? `?${s}` : ""; }
async function parseError(response: Response): Promise<ManagementApiError> { let body: unknown = null; try { body = await response.json(); } catch { body = null; } const d = typeof body === "object" && body && "detail" in body ? (body as { detail?: Record<string, unknown> }).detail : undefined; return new ManagementApiError({ status: response.status, code: String(d?.code ?? `management_${response.status}`), messageKey: String(d?.message_key ?? "management.unknown"), correlationId: typeof d?.correlation_id === "string" ? d.correlation_id : response.headers.get("x-correlation-id") ?? undefined, retryAfter: response.headers.get("retry-after") }); }
async function request<T>(path: string, init: RequestInit & { csrf?: boolean; retry?: boolean } = {}): Promise<T> { const headers = new Headers(init.headers); headers.set("accept", "application/json"); if (init.body) headers.set("content-type", "application/json"); const token = getAccessToken(); if (token) headers.set("authorization", `Bearer ${token}`); if (init.csrf) { const csrf = getCsrfToken(); if (csrf) headers.set("x-csrf-token", csrf); } const res = await fetch(`${API_BASE}/api/v1/admin/management${path}`, { ...init, headers, credentials: "include" }); if (res.status === 401 && init.retry !== false) { await refreshOnce(); return request<T>(path, { ...init, retry: false }); } if (!res.ok) throw await parseError(res); return res.json() as Promise<T>; }
export const managementApi = {
  admins: (q?: Query) => request<Page<AdminRecord>>(`/admins${serializeQuery(q)}`), admin: (id: string) => request<AdminRecord>(`/admins/${encodeURIComponent(id)}`), inviteAdmin: (body: { email: string; role_ids: string[]; expires_in_hours: number }) => request<{ administrator: AdminRecord; invitation_token: string }>("/admins/invitations", { method: "POST", body: JSON.stringify(body), csrf: true }), adminSessions: (id: string) => request<ManagementSession[]>(`/admins/${encodeURIComponent(id)}/sessions`), revokeAdminSession: (adminId: string, sessionId: string) => request<{ok:boolean}>(`/admins/${encodeURIComponent(adminId)}/sessions/${encodeURIComponent(sessionId)}`, { method: "DELETE", csrf: true }), revokeAllAdminSessions: (adminId: string) => request<{ok:boolean}>(`/admins/${encodeURIComponent(adminId)}/sessions`, { method: "DELETE", csrf: true }), setAdminStatus: (id: string, action: "disable"|"lock"|"unlock", reason: string) => request<{ok:boolean}>(`/admins/${encodeURIComponent(id)}/${action}`, { method: "POST", body: JSON.stringify({ reason }), csrf: true }), assignRole: (adminId: string, roleId: string) => request<{ok:boolean}>(`/admins/${encodeURIComponent(adminId)}/roles/${encodeURIComponent(roleId)}`, { method: "POST", csrf: true }), removeRole: (adminId: string, roleId: string) => request<{ok:boolean}>(`/admins/${encodeURIComponent(adminId)}/roles/${encodeURIComponent(roleId)}`, { method: "DELETE", csrf: true }),
  roles: () => request<Page<RoleSummary>>("/roles"), role: (id: string) => request<RoleSummary>(`/roles/${encodeURIComponent(id)}`), createRole: (body: {machine_name:string; display_name:string; description?:string|null}) => request<RoleSummary>("/roles", { method: "POST", body: JSON.stringify(body), csrf: true }), updateRole: (id:string, body: Record<string, unknown>) => request<{ok:boolean}>(`/roles/${encodeURIComponent(id)}`, { method:"PATCH", body: JSON.stringify(body), csrf:true }), rolePermissions: (id:string) => request<Permission[]>(`/roles/${encodeURIComponent(id)}/permissions`), addPermission: (roleId:string, permissionId:string) => request<{ok:boolean}>(`/roles/${encodeURIComponent(roleId)}/permissions/${encodeURIComponent(permissionId)}`, { method:"POST", csrf:true }), removePermission: (roleId:string, permissionId:string) => request<{ok:boolean}>(`/roles/${encodeURIComponent(roleId)}/permissions/${encodeURIComponent(permissionId)}`, { method:"DELETE", csrf:true }), roleAdmins: (id:string) => request<AdminRecord[]>(`/roles/${encodeURIComponent(id)}/admins`), permissions: () => request<Page<Permission>>("/permissions?group=namespace"),
  customers: (q?: Query) => request<Page<Customer>>(`/users${serializeQuery(q)}`), customer: (id:string) => request<Customer>(`/users/${encodeURIComponent(id)}`), setCustomerStatus: (id:string, action:"activate"|"suspend"|"block"|"deactivate", reason:string) => request<{ok:boolean}>(`/users/${encodeURIComponent(id)}/${action}`, { method:"POST", body: JSON.stringify({ reason }), csrf:true }), customerSessions: (id:string) => request<ManagementSession[]>(`/users/${encodeURIComponent(id)}/sessions`), revokeCustomerSession: (userId:string, sessionId:string) => request<{ok:boolean}>(`/users/${encodeURIComponent(userId)}/sessions/${encodeURIComponent(sessionId)}`, { method:"DELETE", csrf:true }), revokeAllCustomerSessions: (userId:string) => request<{ok:boolean}>(`/users/${encodeURIComponent(userId)}/sessions`, { method:"DELETE", csrf:true }),
  auditLogs: (q?: Query) => request<Page<AuditEvent>>(`/audit-logs${serializeQuery(q)}`), auditLog: (id:string) => request<AuditEvent>(`/audit-logs/${encodeURIComponent(id)}`), securityEvents: (q?: Query) => request<Page<SecurityEvent>>(`/security-events${serializeQuery(q)}`), securityEvent: (id:string) => request<SecurityEvent>(`/security-events/${encodeURIComponent(id)}`), acknowledgeSecurityEvent: (id:string) => request<{ok:boolean}>(`/security-events/${encodeURIComponent(id)}/acknowledge`, { method:"POST", csrf:true }), resolveSecurityEvent: (id:string, note:string) => request<{ok:boolean}>(`/security-events/${encodeURIComponent(id)}/resolve`, { method:"POST", body: JSON.stringify({ note: note.slice(0,500) }), csrf:true }), reopenSecurityEvent: (id:string) => request<{ok:boolean}>(`/security-events/${encodeURIComponent(id)}/reopen`, { method:"POST", csrf:true })
};
